# Generated by Django 2.1.2 on 2020-04-05 20:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('socle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoncement', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte de présentation')),
                ('code', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Code*')),
                ('situation', models.PositiveIntegerField(default=10, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations')),
                ('calculator', models.BooleanField(default=0, verbose_name='Calculatrice ?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('width', models.PositiveIntegerField(default=750, verbose_name='Largeur')),
                ('height', models.PositiveIntegerField(default=550, verbose_name='Hauteur')),
                ('ggbfile', models.FileField(default='', upload_to=qcm.models.quiz_directory_path, verbose_name='Fichier ggb')),
                ('imagefile', models.ImageField(default='', upload_to=qcm.models.image_directory_path, verbose_name="Vignette d'accueil")),
                ('toolBar', models.BooleanField(default=0, verbose_name='Barre des outils ?')),
                ('menuBar', models.BooleanField(default=0, verbose_name='Barre de menu ?')),
                ('algebraInput', models.BooleanField(default=0, verbose_name='Multi-fenêtres ?')),
                ('resetIcon', models.BooleanField(default=0, verbose_name='Bouton Reset ?')),
                ('dragZoom', models.BooleanField(default=0, verbose_name='Zoom/déplacement ?')),
                ('is_title', models.BooleanField(default=0, editable=False, verbose_name="titre pour l'organisation des parcours")),
                ('is_subtitle', models.BooleanField(default=0, editable=False, verbose_name="sous-titre pour l'organisation des parcours")),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée - en minutes')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='author_exercise', to='account.Teacher')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_exercise', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_exercise', to='socle.Level', verbose_name='Niveau')),
                ('students', models.ManyToManyField(blank=True, related_name='students_exercise', to='account.Student', verbose_name='Travail fait')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme_exercise', to='socle.Theme', verbose_name='Thème')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('color', models.CharField(default='#00819F', max_length=255, verbose_name='Couleur')),
                ('is_share', models.BooleanField(default=1, verbose_name='partagé ?')),
                ('is_publish', models.BooleanField(default=1, editable=False)),
                ('code', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Code du parcours*')),
                ('linked', models.BooleanField(default=0, editable=False)),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_parcours', to='account.Teacher', verbose_name='Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('is_publish', models.BooleanField(default=1)),
                ('start', models.DateField(blank=True, null=True, verbose_name='A partir de')),
                ('date_limit', models.DateField(blank=True, null=True, verbose_name='Date limite du rendu')),
                ('exercise', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_relationship', to='qcm.Exercise')),
                ('parcours', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='parcours_relationship', to='qcm.Parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Remediation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Titre')),
                ('width', models.PositiveIntegerField(default=500, verbose_name='Largeur')),
                ('height', models.PositiveIntegerField(default=400, verbose_name='Hauteur')),
                ('video', models.CharField(blank=True, default='', max_length=255, verbose_name='Code de la vidéo Youtube')),
                ('mediation', models.FileField(blank=True, default='', upload_to=qcm.models.quiz_directory_path, verbose_name='Fichier')),
                ('sort', models.BooleanField(default=0, verbose_name='Remédiation ? Approfondissement ?')),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée - en minutes')),
                ('exercises', models.ManyToManyField(blank=True, related_name='exercise_remediation', to='qcm.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Resultexercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_resultexercise', to='qcm.Exercise')),
                ('student', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='student_resultexercise', to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Studentanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('numexo', models.PositiveIntegerField(default=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('secondes', models.CharField(editable=False, max_length=255)),
                ('exercise', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ggbfile_studentanswer', to='qcm.Exercise')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='student_studentanswer', to='account.Student')),
            ],
        ),
        migrations.AddField(
            model_name='parcours',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises_parcours', through='qcm.Relationship', to='qcm.Exercise'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_to_parcours', to='account.Student', verbose_name='Elèves de ce parcours'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_parcours', to='account.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('exercise', 'parcours')},
        ),
    ]
