# Generated by Django 3.0.5 on 2020-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='sort',
            field=models.BooleanField(default=0, verbose_name='Type du document'),
        ),
    ]
