# Generated by Django 2.1.2 on 2020-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='beginner',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début de publication'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='duration',
            field=models.PositiveIntegerField(default=15, verbose_name='Durée estimée en minutes'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_evaluation',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='parcours',
            name='situation',
            field=models.PositiveIntegerField(default=10, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='stopper',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin de publication'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='beginner',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure du début'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='duration',
            field=models.PositiveIntegerField(default=15, verbose_name='Durée estimée en minutes'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_evaluation',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='relationship',
            name='situation',
            field=models.PositiveIntegerField(default=10, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations'),
        ),
    ]
