# Generated by Django 2.1.2 on 2020-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_auto_20200411_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='situation',
        ),
        migrations.AddField(
            model_name='parcours',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_publish',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
