# Generated by Django 3.0.5 on 2020-06-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_constraint_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='sort',
        ),
    ]
