# Generated by Django 2.1.2 on 2020-04-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0003_auto_20200411_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcours',
            old_name='beginner',
            new_name='starter',
        ),
        migrations.AddField(
            model_name='parcours',
            name='stop',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de publication'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_evaluation',
            field=models.BooleanField(default=0, verbose_name='Evaluation ?'),
        ),
    ]
