# Generated by Django 3.0.5 on 2020-06-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('qcm', '0003_remove_constraint_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='students',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='parcours',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='account.Student'),
        ),
    ]
