# Generated by Django 2.1.2 on 2020-04-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0004_auto_20200411_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultexercise',
            name='parcours',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours_resultexercice', to='qcm.Parcours'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='parcours',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours_studentanswer', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Temps de chargement (min.)'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début de publication'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='stop',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de publication'),
        ),
    ]
