# Generated by Django 3.0.5 on 2020-06-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_sacado', '0001_initial'),
        ('socle', '0001_initial'),
        ('qcm', '0004_auto_20200605_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='supportfile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='qcm.Supportfile', verbose_name='Fichier Géogebra'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='socle.Theme', verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supportfiles', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supportfiles', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supportfiles', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supportfiles', to='socle.Theme', verbose_name='Thème'),
        ),
    ]
