# Generated by Django 3.0.5 on 2020-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0005_auto_20200606_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=2, verbose_name='Temps de chargement (min.)'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_evaluation',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
