# Generated by Django 2.1.2 on 2020-04-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0005_auto_20200412_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultexercise',
            name='parcours',
        ),
    ]
