# Generated by Django 3.0.5 on 2020-04-20 07:59

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200420_0759'),
        ('qcm', '0006_remove_resultexercise_parcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='vignette',
            field=models.ImageField(blank=True, default='', upload_to=qcm.models.vignette_directory_path, verbose_name="Image d'accueil"),
        ),
        migrations.AlterUniqueTogether(
            name='resultexercise',
            unique_together={('student', 'exercise')},
        ),
    ]
