# Generated by Django 3.0.5 on 2020-06-14 22:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_sacado', '0005_auto_20200612_2212'),
        ('qcm', '0006_auto_20200611_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoncement', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte*')),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée de lecture')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('is_task', models.BooleanField(default=0, verbose_name='Tache à rendre ?')),
                ('is_paired', models.BooleanField(default=0, verbose_name='Révision par les pairs ?')),
                ('is_active', models.BooleanField(default=0, verbose_name='Contenu en cours')),
                ('date_limit', models.DateTimeField(blank=True, null=True, verbose_name='Date limite du rendu')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notification', models.BooleanField(default=0, help_text='Envoie un message aux participants.', verbose_name='Informer des modifications ?')),
                ('creators', models.ManyToManyField(blank=True, related_name='creators_course', to='account.Student', verbose_name='Co auteurs élève')),
                ('parcours', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='qcm.Parcours')),
                ('students', models.ManyToManyField(blank=True, related_name='students_course', to='account.Student', verbose_name='Attribuer à/au')),
                ('teacher', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='account.Teacher')),
            ],
        ),
    ]
