# Generated by Django 3.0.5 on 2020-04-22 10:37

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0007_auto_20200420_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='annoncement',
            field=models.TextField(verbose_name='Précision sur le savoir faire'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='vignette',
            field=models.ImageField(blank=True, default='', upload_to=qcm.models.vignette_directory_path, verbose_name='Image du parcours'),
        ),
    ]
