# Generated by Django 3.0.5 on 2020-04-23 00:17

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('account', '0007_auto_20200420_0759'),
        ('qcm', '0008_auto_20200422_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ggbfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoncement', models.TextField(verbose_name='Précision sur le savoir faire')),
                ('code', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Code*')),
                ('situation', models.PositiveIntegerField(default=10, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations')),
                ('calculator', models.BooleanField(default=0, verbose_name='Calculatrice ?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('width', models.PositiveIntegerField(default=750, verbose_name='Largeur')),
                ('height', models.PositiveIntegerField(default=550, verbose_name='Hauteur')),
                ('ggbfile', models.FileField(default='', upload_to=qcm.models.quiz_directory_path, verbose_name='Fichier ggb')),
                ('imagefile', models.ImageField(default='', upload_to=qcm.models.image_directory_path, verbose_name="Vignette d'accueil")),
                ('toolBar', models.BooleanField(default=0, verbose_name='Barre des outils ?')),
                ('menuBar', models.BooleanField(default=0, verbose_name='Barre de menu ?')),
                ('algebraInput', models.BooleanField(default=0, verbose_name='Multi-fenêtres ?')),
                ('resetIcon', models.BooleanField(default=0, verbose_name='Bouton Reset ?')),
                ('dragZoom', models.BooleanField(default=0, verbose_name='Zoom/déplacement ?')),
                ('is_title', models.BooleanField(default=0, editable=False, verbose_name="titre pour l'organisation des parcours")),
                ('is_subtitle', models.BooleanField(default=0, editable=False, verbose_name="sous-titre pour l'organisation des parcours")),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée - en minutes')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='author_ggbfile', to='account.Teacher')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_ggbfile', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_ggbfile', to='socle.Level', verbose_name='Niveau')),
                ('students', models.ManyToManyField(blank=True, related_name='students_ggbfile', to='account.Student', verbose_name='Travail fait')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme_ggbfile', to='socle.Theme', verbose_name='Thème')),
            ],
        ),
    ]
