# Generated by Django 3.0.5 on 2020-06-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0008_auto_20200615_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Titre'),
        ),
    ]
