# Generated by Django 3.0.5 on 2020-04-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('account', '0007_auto_20200420_0759'),
        ('qcm', '0010_remove_ggbfile_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ggbfile',
            new_name='Supportfile',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='algebraInput',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='annoncement',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='calculator',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='code',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='dragZoom',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='ggbfile',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='height',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='imagefile',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_subtitle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_title',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='menuBar',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='resetIcon',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='toolBar',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='width',
        ),
        migrations.AddField(
            model_name='exercise',
            name='supportfile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='supportfile_exercise', to='qcm.Supportfile', verbose_name='Fichier Géogebra'),
        ),
    ]
