# Generated by Django 3.0.5 on 2020-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0010_auto_20200628_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Ordre'),
        ),
    ]
