# Generated by Django 3.0.5 on 2020-07-29 06:15

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0003_subject_shortname'),
        ('qcm', '0011_course_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Votre demande explicitée*')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('file', models.FileField(default='', upload_to=qcm.models.directory_path, verbose_name='Exercice souhaité')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand', to='socle.Level', verbose_name='Niveau')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand', to='socle.Theme', verbose_name='Thème')),
            ],
        ),
    ]
