# Generated by Django 3.0.5 on 2021-09-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0011_auto_20210919_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='folder_parcours',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='is_folder',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='is_leaf',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='leaf_parcours',
        ),
    ]
