# Generated by Django 3.0.5 on 2021-09-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0012_auto_20210920_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='folder_parcours',
            field=models.ManyToManyField(blank=True, related_name='_parcours_folder_parcours_+', to='qcm.Parcours', verbose_name='Nom de parcours'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_folder',
            field=models.BooleanField(default=0, verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_leaf',
            field=models.BooleanField(default=0, verbose_name='Inclus dans un dossier ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='leaf_parcours',
            field=models.ManyToManyField(blank=True, related_name='_parcours_leaf_parcours_+', to='qcm.Parcours', verbose_name='Nom du dossier'),
        ),
    ]
