# Generated by Django 3.0.5 on 2020-04-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0012_supportfile_knowledges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportfile',
            name='knowledges',
        ),
    ]
