# Generated by Django 3.0.5 on 2020-07-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20200727_1646'),
        ('qcm', '0012_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='teacher',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='demand', to='account.Teacher'),
        ),
    ]
