# Generated by Django 3.0.5 on 2020-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0013_demand_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='demand',
            field=models.TextField(blank=True, verbose_name='Votre demande explicitée*'),
        ),
    ]
