# Generated by Django 3.0.5 on 2020-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('qcm', '0013_remove_supportfile_knowledges'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='knowledges',
            field=models.ManyToManyField(blank=True, related_name='knowledges_supportfile', through='qcm.Exercise', to='socle.Knowledge'),
        ),
    ]
