# Generated by Django 3.0.5 on 2020-04-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200420_0759'),
        ('socle', '0001_initial'),
        ('qcm', '0014_supportfile_knowledges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowledge_exercise', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_exercise', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='supportfile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supportfile_exercise', to='qcm.Supportfile', verbose_name='Fichier Géogebra'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theme_exercise', to='socle.Theme', verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_ggbfile', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='knowledge_ggbfile', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_ggbfile', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='theme_ggbfile', to='socle.Theme', verbose_name='Thème'),
        ),
    ]
