# Generated by Django 3.0.5 on 2020-07-29 07:55

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0014_auto_20200729_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='file',
            field=models.FileField(default='', null=True, upload_to=qcm.models.directory_path, verbose_name='Exercice souhaité'),
        ),
    ]
