# Generated by Django 3.0.5 on 2020-04-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('qcm', '0015_auto_20200423_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('knowledge', 'supportfile')},
        ),
    ]
