# Generated by Django 3.0.5 on 2020-07-29 08:01

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0015_auto_20200729_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='done',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Fait'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=qcm.models.directory_path, verbose_name='Exercice souhaité'),
        ),
    ]
