# Generated by Django 3.0.5 on 2020-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0016_auto_20200729_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name="id de l'exercice créé"),
        ),
    ]
