# Generated by Django 3.0.5 on 2020-04-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200425_1417'),
        ('socle', '0001_initial'),
        ('qcm', '0016_auto_20200423_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportfile',
            name='knowledges',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_exercise', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_exercise', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='supportfile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='supportfile_exercise', to='qcm.Supportfile', verbose_name='Fichier Géogebra'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme_exercise', to='socle.Theme', verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='exercise',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_relationship', to='qcm.Exercise'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='parcours',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='parcours_relationship', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='resultexercise',
            name='student',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultexercise', to='account.Student'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_studentanswer', to='account.Student'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='author_ggbfile', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_ggbfile', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_ggbfile', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theme_ggbfile', to='socle.Theme', verbose_name='Thème'),
        ),
    ]
