# Generated by Django 3.0.5 on 2020-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0017_auto_20200425_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='favori',
            field=models.BooleanField(default=1, verbose_name='Favori ?'),
        ),
    ]
