# Generated by Django 3.0.5 on 2020-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0017_demand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_share',
            field=models.BooleanField(default=1, verbose_name='Mutualisé ?'),
        ),
    ]
