# Generated by Django 3.0.5 on 2020-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0018_auto_20200829_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_archive',
            field=models.BooleanField(default=0, verbose_name='Archiver ?'),
        ),
    ]
