# Generated by Django 3.0.5 on 2020-08-30 16:19

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20200727_1646'),
        ('qcm', '0019_parcours_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_archive',
            field=models.BooleanField(default=0, verbose_name='Archivé ?'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_share',
            field=models.BooleanField(default=0, verbose_name='Mutualisé ?'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_to_parcours', to='account.Student', verbose_name='Elèves'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='vignette',
            field=models.ImageField(blank=True, default='', upload_to=qcm.models.vignette_directory_path, verbose_name="Vignette d'accueil"),
        ),
    ]
