# Generated by Django 3.0.5 on 2020-05-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('qcm', '0020_auto_20200504_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill_relationship', to='socle.Skill'),
        ),
    ]
