# Generated by Django 3.0.5 on 2020-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0020_auto_20200830_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_archive',
            field=models.BooleanField(default=0, editable=False, verbose_name='Archivé ?'),
        ),
    ]
