# Generated by Django 3.0.5 on 2020-09-15 07:17

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0021_auto_20200913_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='attach_file',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.file_attach_path, verbose_name='Fichier pdf attaché'),
        ),
    ]
