# Generated by Django 3.0.5 on 2020-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('qcm', '0021_relationship_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='skill',
        ),
        migrations.AddField(
            model_name='relationship',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills_relationship', to='socle.Skill'),
        ),
    ]
