# Generated by Django 3.0.5 on 2020-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('qcm', '0022_auto_20200516_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='skills',
            field=models.ManyToManyField(blank=True, editable=False, related_name='skills_relationship', to='socle.Skill'),
        ),
    ]
