# Generated by Django 3.0.5 on 2020-09-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0022_supportfile_attach_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='supportfiles',
            field=models.ManyToManyField(blank=True, related_name='supportfiles_course', to='qcm.Supportfile', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='is_subtitle',
            field=models.BooleanField(default=0, verbose_name="sous-titre pour l'organisation des parcours"),
        ),
    ]
