# Generated by Django 3.0.5 on 2020-09-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0023_auto_20200916_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='supportfiles',
        ),
        migrations.AddField(
            model_name='course',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='relationships_course', to='qcm.Relationship', verbose_name='Lier ce cours à ces sections'),
        ),
    ]
