# Generated by Django 3.0.5 on 2020-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('qcm', '0023_auto_20200516_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills_supportfile', to='socle.Skill'),
        ),
    ]
