# Generated by Django 3.0.5 on 2020-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('qcm', '0024_supportfile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills_supportfile', to='socle.Skill', verbose_name='Compétences ciblées'),
        ),
    ]
