# Generated by Django 3.0.5 on 2020-09-27 17:05

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0024_auto_20200916_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consigne', models.CharField(blank=True, default='', max_length=255, verbose_name='Consigne')),
                ('video', models.CharField(blank=True, default='', max_length=50, verbose_name='code de vidéo Youtube')),
                ('mediation', models.FileField(blank=True, default='', null=True, upload_to=qcm.models.directory_path_mastering, verbose_name='Fichier')),
                ('writing', models.BooleanField(default=0, verbose_name="Page d'écriture")),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée')),
                ('scale', models.PositiveIntegerField(default=3, editable=False)),
                ('ranking', models.PositiveIntegerField(default=0, editable=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='courses_mastering', to='qcm.Course')),
                ('exercise', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='exercise', to='qcm.Exercise')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationship_mastering', to='qcm.Relationship', verbose_name='Exercice')),
            ],
        ),
    ]
