# Generated by Django 3.0.5 on 2020-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200518_1736'),
        ('qcm', '0025_auto_20200517_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='students_relationship', to='account.Student'),
        ),
    ]
