# Generated by Django 3.0.5 on 2020-09-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0025_mastering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastering',
            name='exercise',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercise', to='qcm.Exercise'),
        ),
    ]
