# Generated by Django 3.0.5 on 2020-09-28 12:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20200727_1646'),
        ('qcm', '0026_auto_20200927_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastering_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte*')),
                ('mastering', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='mastering_done', to='qcm.Mastering', verbose_name='Exercice')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='students_mastering_done', to='account.Student')),
            ],
        ),
    ]
