# Generated by Django 3.0.5 on 2020-05-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0026_relationship_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='students',
        ),
    ]
