# Generated by Django 3.0.5 on 2020-10-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0027_mastering_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='written_answer',
            field=models.BooleanField(default=0, verbose_name='Réponse rédigée ?'),
        ),
    ]
