# Generated by Django 3.0.5 on 2020-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200518_1814'),
        ('qcm', '0027_remove_relationship_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='students_relationship', to='account.Student'),
        ),
    ]
