# Generated by Django 3.0.5 on 2020-05-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0028_relationship_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediation',
            name='exercises',
        ),
        migrations.AddField(
            model_name='remediation',
            name='relationship',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_remediation', to='qcm.Relationship'),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='sort',
            field=models.BooleanField(default=0, verbose_name='Type ? '),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='video',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='url de la vidéo'),
        ),
    ]
