# Generated by Django 3.0.5 on 2020-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0028_supportfile_written_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='written_answer',
            field=models.BooleanField(default=1, verbose_name='Type de support'),
        ),
    ]
