# Generated by Django 3.0.5 on 2020-05-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('qcm', '0029_auto_20200521_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='level',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_parcours', to='socle.Level'),
        ),
    ]
