# Generated by Django 3.0.5 on 2020-10-13 19:34

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0029_auto_20201013_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='ggbfile',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.quiz_directory_path, verbose_name='Fichier ggb'),
        ),
    ]
