# Generated by Django 3.0.5 on 2020-05-23 12:36

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0030_parcours_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediation',
            name='height',
        ),
        migrations.RemoveField(
            model_name='remediation',
            name='width',
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_publish',
            field=models.BooleanField(default=0, verbose_name='Publié ?'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_share',
            field=models.BooleanField(default=1, verbose_name='Partagé ?'),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='duration',
            field=models.PositiveIntegerField(default=15, verbose_name='Durée estimée (en min.)'),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='mediation',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.file_directory_path, verbose_name='Fichier - pdf'),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='sort',
            field=models.BooleanField(default=0, verbose_name='Type du document'),
        ),
    ]
