# Generated by Django 3.0.5 on 2020-10-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0030_auto_20201013_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportfile',
            old_name='written_answer',
            new_name='is_ggbfile',
        ),
    ]
