# Generated by Django 3.0.5 on 2020-05-24 13:56

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0031_auto_20200523_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='code',
            field=models.CharField(blank=True, default=qcm.models.generate_code, max_length=100, unique=True, verbose_name='Code du parcours*'),
        ),
    ]
