# Generated by Django 3.0.5 on 2022-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0031_relationship_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='forme',
            field=models.CharField(blank=True, choices=[('COURS', 'COURS'), ('METHODE', 'METHODE'), ('EXEMPLE', 'EXEMPLE'), ('VIDEO', 'VIDEO'), ('', 'PRESENTATION')], default='COURS', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
