# Generated by Django 3.0.5 on 2022-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0031_relationship_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='forme',
            field=models.CharField(blank=True, choices=[('ACTIVITE', 'ACTIVITE'), ('APPLICATION', 'APPLICATION'), ('COURS', 'COURS'), ('CONSIGNE', 'CONSIGNE'), ('EXEMPLE', 'EXEMPLE'), ('EXPLICATION', 'EXPLICATION'), ('HISTOIRE', 'HISTOIRE'), ('ILLUSTRATION', 'ILLUSTRATION'), ('MÉTHODE', 'MÉTHODE'), ('', 'PRESENTATION'), ('VIDEO', 'VIDEO')], default='COURS', max_length=50, verbose_name='Type'),
        ),
    ]
