# Generated by Django 3.0.5 on 2020-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0031_auto_20201013_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='instruction',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
