# Generated by Django 3.0.5 on 2020-05-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0032_auto_20200524_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='under_contraint',
            field=models.BooleanField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Contraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', editable=False, max_length=8)),
                ('scoremin', models.PositiveIntegerField(default=80, editable=False)),
                ('relationship', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_contraint', to='qcm.Relationship')),
            ],
        ),
    ]
