# Generated by Django 3.0.5 on 2020-10-14 20:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0032_relationship_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answercomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte*')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_answer', to='qcm.Relationship')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_answer', to='account.Student')),
            ],
        ),
    ]
