# Generated by Django 3.0.5 on 2020-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0033_answercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='writing',
        ),
        migrations.AddField(
            model_name='answercomment',
            name='comment',
            field=models.TextField(default='', editable=False),
        ),
    ]
