# Generated by Django 3.0.5 on 2020-05-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200524_0921'),
        ('socle', '0002_skill'),
        ('qcm', '0033_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='socle.Knowledge', verbose_name='Savoir faire associé - Titre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='account.Student', verbose_name='Travail fait'),
        ),
    ]
