# Generated by Django 3.0.5 on 2020-05-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0033_auto_20200526_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='under_contraint',
        ),
    ]
