# Generated by Django 3.0.5 on 2022-10-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0033_auto_20220919_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='ia',
            field=models.BooleanField(default=0, verbose_name='IA ?'),
        ),
    ]
