# Generated by Django 3.0.5 on 2020-10-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0033_auto_20201018_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customanswerbystudent',
            name='notification',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
