# Generated by Django 3.0.5 on 2020-10-15 10:07

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0034_auto_20201014_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writtenanswerbystudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('imagefile', models.ImageField(blank=True, default='', upload_to=qcm.models.file_directory_student, verbose_name='Scan ou image ou Photo')),
                ('answer', models.TextField(blank=True, default='')),
                ('relationship', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_written_answer', to='qcm.Relationship')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_written_answer', to='account.Student')),
            ],
        ),
    ]
