# Generated by Django 3.0.5 on 2020-10-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0034_customanswerbystudent_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customanswerbystudent',
            old_name='notification',
            new_name='is_corrected',
        ),
    ]
