# Generated by Django 3.0.5 on 2022-10-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0034_parcours_ia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcours',
            old_name='ia',
            new_name='is_ia',
        ),
    ]
