# Generated by Django 3.0.5 on 2020-05-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200530_0717'),
        ('qcm', '0035_auto_20200528_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultexercise',
            name='exercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='results_e', to='qcm.Exercise'),
        ),
        migrations.AlterField(
            model_name='resultexercise',
            name='student',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results_e', to='account.Student'),
        ),
    ]
