# Generated by Django 3.0.5 on 2020-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0035_auto_20201018_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanswerbystudent',
            name='point',
            field=models.CharField(default='', max_length=10, verbose_name='Note'),
        ),
    ]
