# Generated by Django 3.0.5 on 2020-10-15 10:36

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0035_writtenanswerbystudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='comment',
            field=models.TextField(default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='writtenanswerbystudent',
            name='answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='writtenanswerbystudent',
            name='imagefile',
            field=models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.file_directory_student, verbose_name='Scan ou image ou Photo'),
        ),
    ]
