# Generated by Django 3.0.5 on 2022-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0035_auto_20221012_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_ia',
            field=models.BooleanField(default=0, verbose_name='Intelligence Artificielle ?'),
        ),
    ]
