# Generated by Django 3.0.5 on 2020-10-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0036_auto_20201019_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionknowledgecustomexercise',
            name='point',
            field=models.PositiveIntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='correctionskillcustomexercise',
            name='point',
            field=models.PositiveIntegerField(default=-1, editable=False),
        ),
    ]
