# Generated by Django 3.0.5 on 2022-10-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0036_auto_20221017_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselocker',
            name='code',
        ),
    ]
