# Generated by Django 3.0.5 on 2020-10-15 15:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0036_auto_20201015_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='is_file',
            field=models.BooleanField(default=0, verbose_name='Fichier ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_image',
            field=models.BooleanField(default=0, verbose_name='Iage/Scan ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_python',
            field=models.BooleanField(default=0, verbose_name='Python ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_scratch',
            field=models.BooleanField(default=0, verbose_name='Scratch ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_text',
            field=models.BooleanField(default=0, verbose_name='Texte ?'),
        ),
        migrations.AlterField(
            model_name='writtenanswerbystudent',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
    ]
