# Generated by Django 3.0.5 on 2020-10-20 18:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0037_auto_20201020_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Consigne*'),
        ),
    ]
