# Generated by Django 3.0.5 on 2022-11-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0037_remove_exerciselocker_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.CharField(max_length=255, verbose_name='features')),
                ('targets', models.CharField(max_length=255, verbose_name='labels')),
                ('test_effective', models.CharField(max_length=255, verbose_name='test choisi')),
            ],
        ),
        migrations.CreateModel(
            name='Testtraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.CharField(max_length=255, verbose_name='features')),
                ('targets', models.CharField(max_length=255, verbose_name='labels')),
                ('test_proposed', models.CharField(max_length=255, verbose_name='proposition')),
                ('test_effective', models.CharField(max_length=255, verbose_name='test choisi')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parcours', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='qcm.Parcours', unique=True, verbose_name='parcours')),
            ],
        ),
    ]
