# Generated by Django 3.0.5 on 2022-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0038_testcreator_testtraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtraining',
            name='parcours',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='testtraining', to='qcm.Parcours', verbose_name='parcours'),
        ),
    ]
