# Generated by Django 3.0.5 on 2020-10-21 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0038_auto_20201020_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
