# Generated by Django 3.0.5 on 2020-10-21 15:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0039_auto_20201021_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masteringcustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consigne', models.CharField(blank=True, default='', max_length=255, verbose_name='Consigne')),
                ('video', models.CharField(blank=True, default='', max_length=50, verbose_name='code de vidéo Youtube')),
                ('mediation', models.FileField(blank=True, default='', null=True, upload_to=qcm.models.directory_path_mastering, verbose_name='Fichier')),
                ('writing', models.BooleanField(default=0, verbose_name="Page d'écriture")),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée')),
                ('scale', models.PositiveIntegerField(default=3, editable=False)),
                ('ranking', models.PositiveIntegerField(default=0, editable=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='courses_mastering_custom', to='qcm.Course')),
                ('customexercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customexercise_mastering_custom', to='qcm.Customexercise', verbose_name='Exercice')),
                ('exercise', models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_mastering_custom', to='qcm.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Masteringcustom_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte*')),
                ('mastering', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='mastering_custom_done', to='qcm.Masteringcustom', verbose_name='Exercice')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='students_mastering_custom_done', to='account.Student')),
            ],
        ),
    ]
