# Generated by Django 3.0.5 on 2022-11-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0039_auto_20221101_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtraining',
            name='parcours',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testtraining', to='qcm.Parcours', verbose_name='parcours'),
        ),
        migrations.AlterField(
            model_name='testtraining',
            name='targets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='labels'),
        ),
        migrations.AlterField(
            model_name='testtraining',
            name='test_effective',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='test choisi'),
        ),
        migrations.AlterField(
            model_name='testtraining',
            name='test_proposed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='proposition'),
        ),
    ]
