# Generated by Django 3.0.5 on 2020-10-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0040_masteringcustom_masteringcustom_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='starter',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='stopper',
        ),
        migrations.AlterField(
            model_name='parcours',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début de publication'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillée à partir de'),
        ),
    ]
