# Generated by Django 3.0.5 on 2022-11-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0040_auto_20221101_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtraining',
            old_name='test_effective',
            new_name='quizz_effective',
        ),
        migrations.RenameField(
            model_name='testtraining',
            old_name='test_proposed',
            new_name='quizz_proposed',
        ),
    ]
