# Generated by Django 3.0.5 on 2022-11-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0041_auto_20221101_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcreator',
            old_name='test_effective',
            new_name='questions_effective',
        ),
        migrations.RenameField(
            model_name='testtraining',
            old_name='quizz_effective',
            new_name='questions_effective',
        ),
        migrations.RenameField(
            model_name='testtraining',
            old_name='quizz_proposed',
            new_name='questions_proposed',
        ),
    ]
