# Generated by Django 3.0.5 on 2020-10-22 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0041_auto_20201022_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish_end',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='Se termine à'),
        ),
        migrations.AlterField(
            model_name='course',
            name='publish_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Changer les dates des cours peut remplacer les réglages de leur durée de disponibilité et leur placement dans les pages de cours ou le tableau de bord. Veuillez confirmer les dates d’échéance avant de modifier les dates des cours. ', max_length=255, verbose_name='Début à'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='date_limit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date limite du rendu'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='A partir de'),
        ),
    ]
