# Generated by Django 3.0.5 on 2020-10-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0042_auto_20201022_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='instruction',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
