# Generated by Django 3.0.5 on 2022-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0042_auto_20221102_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_testpos',
            field=models.BooleanField(default=0, editable=False, verbose_name='Test de positionnement ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='target',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Parcours cible'),
        ),
    ]
