# Generated by Django 3.0.5 on 2020-10-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0043_auto_20201023_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='is_share',
            field=models.BooleanField(default=0, verbose_name='Mutualisé ?'),
        ),
    ]
