# Generated by Django 3.0.5 on 2022-11-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0043_auto_20221114_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcours',
            old_name='target',
            new_name='target_id',
        ),
    ]
