# Generated by Django 3.0.5 on 2020-10-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0044_customexercise_is_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_share',
            field=models.BooleanField(default=0, verbose_name='Mutualisé ?'),
        ),
    ]
