# Generated by Django 3.0.5 on 2022-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0044_auto_20221114_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtraining',
            name='questions_effective',
            field=models.TextField(blank=True, null=True, verbose_name='test choisi'),
        ),
        migrations.AlterField(
            model_name='testtraining',
            name='questions_proposed',
            field=models.TextField(blank=True, null=True, verbose_name='proposition'),
        ),
    ]
