# Generated by Django 3.0.5 on 2020-10-27 22:59

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0045_course_is_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée (en min.)'),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='mediation',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.file_directory_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='remediation',
            name='sort',
            field=models.BooleanField(default=0, verbose_name='Audio texte ?'),
        ),
    ]
