# Generated by Django 3.0.5 on 2020-10-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0046_auto_20201027_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remediation',
            old_name='sort',
            new_name='audio',
        ),
    ]
