# Generated by Django 3.0.5 on 2022-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0047_auto_20221119_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcourscreator',
            name='parcours_id',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='parcourscreator',
            name='student_id',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
