# Generated by Django 3.0.5 on 2020-10-28 10:59

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0048_auto_20201028_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanswerbystudent',
            name='audio',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.file_folder_path, verbose_name='Commentaire audio'),
        ),
    ]
