# Generated by Django 3.0.5 on 2022-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0048_auto_20221120_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcourscreator',
            name='effective',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
