# Generated by Django 3.0.5 on 2020-10-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0049_auto_20201028_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenanswerbystudent',
            name='is_corrected',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
