# Generated by Django 3.0.5 on 2022-11-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_connexion'),
        ('socle', '0008_level_is_active'),
        ('qcm', '0049_parcourscreator_effective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledgegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('is_homogene', models.BooleanField(default=0, editable=False)),
                ('knowledges', models.ManyToManyField(blank=True, editable=False, related_name='knowledge_groups', to='socle.Knowledge')),
                ('parcours', models.ManyToManyField(blank=True, related_name='knowledge_groups', to='qcm.Parcours')),
                ('students', models.ManyToManyField(blank=True, editable=False, related_name='knowledge_groups', to='account.Student')),
            ],
        ),
    ]
