# Generated by Django 3.0.5 on 2020-10-29 13:39

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0050_writtenanswerbystudent_is_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediation',
            name='consigne',
            field=models.BooleanField(default=0, verbose_name='Consigne ?'),
        ),
        migrations.AlterField(
            model_name='customanswerbystudent',
            name='audio',
            field=models.FileField(blank=True, default='', null=True, upload_to=qcm.models.file_folder_path, verbose_name='Commentaire audio'),
        ),
        migrations.AlterField(
            model_name='writtenanswerbystudent',
            name='audio',
            field=models.FileField(blank=True, default='', null=True, upload_to=qcm.models.file_directory_path, verbose_name='Commentaire audio'),
        ),
    ]
