# Generated by Django 3.0.5 on 2020-10-29 14:28

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0051_auto_20201029_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remediationcustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Titre')),
                ('video', models.CharField(blank=True, default='', max_length=255, verbose_name='url de la vidéo')),
                ('mediation', models.FileField(blank=True, default='', upload_to=qcm.models.file_directory_path, verbose_name='Fichier')),
                ('audio', models.BooleanField(default=0, verbose_name='Audio texte ?')),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée (en min.)')),
                ('consigne', models.BooleanField(default=0, verbose_name='Consigne ?')),
                ('customexercise', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='customexercise_remediation', to='qcm.Customexercise')),
            ],
        ),
    ]
