# Generated by Django 3.0.5 on 2020-10-30 01:07

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0004_auto_20201024_2140'),
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0052_remediationcustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationcustom',
            name='mediation',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.file_folder_path, verbose_name='Fichier'),
        ),
        migrations.CreateModel(
            name='Resultggbskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('relationship', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_resultggbskills', to='qcm.Relationship')),
                ('skill', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='skill_resultggbskills', to='socle.Skill')),
                ('student', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultggbskills', to='account.Student')),
            ],
        ),
    ]
