# Generated by Django 3.0.5 on 2022-11-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0052_auto_20221123_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegroup',
            name='stamp',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
