# Generated by Django 3.0.5 on 2020-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0053_auto_20201030_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='remediation',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses_remediation', to='qcm.Course', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='remediationcustom',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses_remediationcustom', to='qcm.Course', verbose_name='Cours'),
        ),
    ]
