# Generated by Django 3.0.5 on 2022-12-12 18:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
        ('qcm', '0053_knowledgegroup_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.custom_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Rétroaction')),
                ('imageanswerbis', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.custom_directory_path, verbose_name='Image par paire')),
                ('answerbis', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse par paire')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
            ],
        ),
        migrations.CreateModel(
            name='Customvariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='variable')),
                ('is_integer', models.BooleanField(default=1, verbose_name='Valeur entière ?')),
                ('maximum', models.IntegerField(default=10)),
                ('minimum', models.IntegerField(default=0)),
                ('words', models.CharField(blank=True, max_length=255, verbose_name='Liste de valeurs')),
            ],
        ),
        migrations.AddField(
            model_name='customexercise',
            name='audio',
            field=models.FileField(blank=True, default='', upload_to=qcm.models.custom_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='filltheblanks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Texte à trous'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='is_correct',
            field=models.BooleanField(default=1, verbose_name='Réponse correcte ?'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, related_name='customexercises', to='socle.Level', verbose_name='Niveaux cibles'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='Précision'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='pseudoalea_nb',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='qtype',
            field=models.PositiveIntegerField(default=2, editable=False),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customexercises', to='socle.Subject'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='tick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='video',
            field=models.TextField(blank=True, default='', verbose_name='Vidéo intégrée'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='xmax',
            field=models.FloatField(blank=True, null=True, verbose_name='x max '),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='xmin',
            field=models.FloatField(blank=True, null=True, verbose_name='x min '),
        ),
        migrations.CreateModel(
            name='CustomvariableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=qcm.models.custom_directory_path, verbose_name='Image')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customvariables_img', to='qcm.Customvariable')),
            ],
        ),
        migrations.AddField(
            model_name='customvariable',
            name='customexercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customvariables', to='qcm.Customexercise'),
        ),
        migrations.CreateModel(
            name='Customsubchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.custom_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Rétroaction')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('customchoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customsubchoices', to='qcm.Customchoice')),
            ],
        ),
        migrations.AddField(
            model_name='customchoice',
            name='customexercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customchoices', to='qcm.Customexercise'),
        ),
    ]
