# Generated by Django 3.0.5 on 2020-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0054_auto_20201030_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remediation',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='remediationcustom',
            name='courses',
        ),
        migrations.AddField(
            model_name='remediation',
            name='is_course',
            field=models.BooleanField(default=0, verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='remediationcustom',
            name='is_course',
            field=models.BooleanField(default=0, verbose_name='Cours'),
        ),
    ]
