# Generated by Django 3.0.5 on 2022-12-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
        ('qcm', '0054_auto_20221212_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='customexercises', to='socle.Level', verbose_name='Niveaux cibles'),
        ),
    ]
