# Generated by Django 3.0.5 on 2022-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
        ('qcm', '0055_auto_20221212_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse attendue'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='is_audio',
            field=models.BooleanField(default=0, verbose_name='Audio ?'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='is_video',
            field=models.BooleanField(default=0, verbose_name='Vidéo ?'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='customexercises', to='socle.Theme', verbose_name='Thèmes cibles'),
        ),
    ]
