# Generated by Django 3.0.5 on 2022-12-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0056_auto_20221213_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvariable',
            name='is_notnull',
            field=models.BooleanField(default=1, verbose_name='Exclure 0 ?'),
        ),
    ]
