# Generated by Django 3.0.5 on 2020-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0056_auto_20201030_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediation',
            name='video',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='url de la vidéo'),
        ),
        migrations.AlterField(
            model_name='remediationcustom',
            name='video',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='url de la vidéo'),
        ),
    ]
