# Generated by Django 3.0.5 on 2020-11-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0058_auto_20201030_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customannotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consigne', models.CharField(editable=False, max_length=255)),
                ('classe', models.CharField(editable=False, max_length=255)),
                ('style', models.CharField(editable=False, max_length=255)),
                ('attr_id', models.CharField(editable=False, max_length=255)),
                ('content', models.TextField(editable=False)),
                ('customanswerbystudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='qcm.Customanswerbystudent')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consigne', models.CharField(editable=False, max_length=255)),
                ('classe', models.CharField(editable=False, max_length=255)),
                ('style', models.CharField(editable=False, max_length=255)),
                ('attr_id', models.CharField(editable=False, max_length=255)),
                ('content', models.TextField(editable=False)),
                ('writtenanswerbystudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='qcm.Writtenanswerbystudent')),
            ],
        ),
    ]
