# Generated by Django 3.0.5 on 2022-12-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0058_customexercise_figure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customexercise',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='figure',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='is_audio',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='video',
        ),
    ]
