# Generated by Django 3.0.5 on 2020-11-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0059_annotation_customannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='teacher',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_annotation', to='account.Teacher'),
        ),
        migrations.AddField(
            model_name='customannotation',
            name='teacher',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_customannotation', to='account.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('writtenanswerbystudent', 'attr_id', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='customannotation',
            unique_together={('customanswerbystudent', 'attr_id', 'teacher')},
        ),
    ]
