# Generated by Django 3.0.5 on 2022-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0060_customexercise_canvasimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsubchoice',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='customchoice',
            name='answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite'),
        ),
        migrations.AlterField(
            model_name='customchoice',
            name='retroaction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction'),
        ),
        migrations.AlterField(
            model_name='customsubchoice',
            name='answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite'),
        ),
        migrations.AlterField(
            model_name='customsubchoice',
            name='retroaction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction'),
        ),
    ]
