# Generated by Django 3.0.5 on 2020-11-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0060_auto_20201103_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('writtenanswerbystudent', 'attr_id')},
        ),
        migrations.AlterUniqueTogether(
            name='customannotation',
            unique_together={('customanswerbystudent', 'attr_id')},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='customannotation',
            name='teacher',
        ),
    ]
