# Generated by Django 3.0.5 on 2020-11-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0061_auto_20201103_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='consigne',
        ),
        migrations.RemoveField(
            model_name='customannotation',
            name='consigne',
        ),
    ]
