# Generated by Django 3.0.5 on 2022-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0061_auto_20221215_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='qtype',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
