# Generated by Django 3.0.5 on 2022-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0062_auto_20221215_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
