# Generated by Django 3.0.5 on 2020-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0062_auto_20201103_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='nbannotation',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='nbdivclone',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='customannotation',
            name='nbannotation',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='customannotation',
            name='nbdivclone',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
