# Generated by Django 3.0.5 on 2022-12-22 17:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0063_customexercise_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Consigne*'),
        ),
    ]
