# Generated by Django 3.0.5 on 2020-11-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0063_auto_20201103_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='nbannotation',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='nbdivclone',
        ),
        migrations.RemoveField(
            model_name='customannotation',
            name='nbannotation',
        ),
        migrations.RemoveField(
            model_name='customannotation',
            name='nbdivclone',
        ),
    ]
