# Generated by Django 3.0.5 on 2022-12-26 08:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0064_auto_20221222_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supportchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.vignette_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction')),
                ('imageanswerbis', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.vignette_directory_path, verbose_name='Image par paire')),
                ('answerbis', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse par paire')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
            ],
        ),
        migrations.CreateModel(
            name='Supportvariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='variable')),
                ('is_integer', models.BooleanField(default=1, verbose_name='Valeur entière ?')),
                ('is_notnull', models.BooleanField(default=1, verbose_name='Exclure 0 ?')),
                ('maximum', models.IntegerField(default=10)),
                ('minimum', models.IntegerField(default=0)),
                ('words', models.CharField(blank=True, max_length=255, verbose_name='Liste de valeurs')),
            ],
        ),
        migrations.AddField(
            model_name='supportfile',
            name='canvasimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.image_directory_path, verbose_name='Image support'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='criterions',
            field=models.ManyToManyField(blank=True, related_name='supportfiles', to='qcm.Criterion'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_autocorrection',
            field=models.BooleanField(default=0, verbose_name='Autocorrection ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_collaborative',
            field=models.BooleanField(default=0, verbose_name='Collaboratif ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_mark',
            field=models.BooleanField(default=0, verbose_name='Notation ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_realtime',
            field=models.BooleanField(default=0, verbose_name='Temps réel ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='is_share',
            field=models.BooleanField(default=1, verbose_name='Mutualisé ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='mark',
            field=models.PositiveIntegerField(default=0, verbose_name='Sur ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='Précision'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='qtype',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='tick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='xmax',
            field=models.FloatField(blank=True, null=True, verbose_name='x max '),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='xmin',
            field=models.FloatField(blank=True, null=True, verbose_name='x min '),
        ),
        migrations.AlterField(
            model_name='customexercise',
            name='pseudoalea_nb',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='annoncement',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Consigne'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='imagefile',
            field=models.ImageField(blank=True, default='', upload_to=qcm.models.image_directory_path, verbose_name="Vignette d'accueil"),
        ),
        migrations.CreateModel(
            name='SupportvariableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=qcm.models.vignette_directory_path, verbose_name='Image')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportvariables_img', to='qcm.Supportvariable')),
            ],
        ),
        migrations.AddField(
            model_name='supportvariable',
            name='supporfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportvariables', to='qcm.Supportfile'),
        ),
        migrations.CreateModel(
            name='Supportsubchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.vignette_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', null=True, verbose_name='Rétroaction')),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Label')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('supportchoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customsubchoices', to='qcm.Supportchoice')),
            ],
        ),
        migrations.AddField(
            model_name='supportchoice',
            name='supportfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportchoices', to='qcm.Supportfile'),
        ),
    ]
