# Generated by Django 3.0.5 on 2020-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0064_auto_20201103_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='textarea_style',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='customannotation',
            name='textarea_style',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
