# Generated by Django 3.0.5 on 2022-12-26 19:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0065_auto_20221226_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='annoncement',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Consigne'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée'),
        ),
    ]
