# Generated by Django 3.0.5 on 2020-11-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0065_auto_20201104_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='textarea_style',
        ),
        migrations.RemoveField(
            model_name='customannotation',
            name='textarea_style',
        ),
    ]
