# Generated by Django 3.0.5 on 2020-11-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0066_auto_20201104_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_customexercises', to='account.Teacher'),
        ),
    ]
