# Generated by Django 3.0.5 on 2022-12-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0066_auto_20221226_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportfile',
            name='is_autocorrection',
        ),
        migrations.RemoveField(
            model_name='supportfile',
            name='is_collaborative',
        ),
        migrations.RemoveField(
            model_name='supportfile',
            name='is_mark',
        ),
        migrations.RemoveField(
            model_name='supportfile',
            name='mark',
        ),
    ]
