# Generated by Django 3.0.5 on 2022-12-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0067_auto_20221226_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=550, verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='situation',
            field=models.PositiveIntegerField(default=5, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=750, verbose_name='Largeur'),
        ),
    ]
