# Generated by Django 3.0.5 on 2020-11-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0004_auto_20201024_2140'),
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0067_auto_20201110_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionknowledgecustomexercise',
            name='customexercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customexercise_correctionknowledge', to='qcm.Customexercise'),
        ),
        migrations.AlterField(
            model_name='correctionknowledgecustomexercise',
            name='knowledge',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_correctionknowledge', to='socle.Knowledge'),
        ),
        migrations.AlterField(
            model_name='correctionknowledgecustomexercise',
            name='parcours',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='parcours_customknowledge_answer', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='correctionskillcustomexercise',
            name='customexercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customexercise_correctionskill', to='qcm.Customexercise'),
        ),
        migrations.AlterField(
            model_name='correctionskillcustomexercise',
            name='parcours',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='parcours_customskill_answer', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='correctionskillcustomexercise',
            name='skill',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='skill_correctionskill', to='socle.Skill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='parcours',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='customanswerbystudent',
            name='customexercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customexercise_custom_answer', to='qcm.Customexercise'),
        ),
        migrations.AlterField(
            model_name='customanswerbystudent',
            name='parcours',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='parcours_custom_answer', to='qcm.Parcours'),
        ),
    ]
