# Generated by Django 3.0.5 on 2020-11-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0068_auto_20201110_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='coteachers',
            field=models.ManyToManyField(blank=True, related_name='coteacher_parcours', to='account.Teacher', verbose_name='Enseignant en co-animation'),
        ),
    ]
