# Generated by Django 3.0.5 on 2022-12-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0068_auto_20221226_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportsubchoice',
            name='supportchoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportsubchoices', to='qcm.Supportchoice'),
        ),
    ]
