# Generated by Django 3.0.5 on 2022-12-27 00:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0069_auto_20221227_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsubchoice',
            name='customchoice',
        ),
        migrations.RemoveField(
            model_name='customvariable',
            name='customexercise',
        ),
        migrations.RemoveField(
            model_name='customvariableimage',
            name='variable',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='canvasimage',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='filltheblanks',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='pseudoalea_nb',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='qtype',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='tick',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='title',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='xmax',
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='xmin',
        ),
        migrations.AlterField(
            model_name='customexercise',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Consigne*'),
        ),
        migrations.DeleteModel(
            name='Customchoice',
        ),
        migrations.DeleteModel(
            name='Customsubchoice',
        ),
        migrations.DeleteModel(
            name='Customvariable',
        ),
        migrations.DeleteModel(
            name='CustomvariableImage',
        ),
    ]
