# Generated by Django 3.0.5 on 2020-11-12 15:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0069_parcours_coteachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='text_cor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Correction écrite'),
        ),
    ]
