# Generated by Django 3.0.5 on 2022-12-27 00:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0070_auto_20221227_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='instruction',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Consigne*'),
        ),
    ]
