# Generated by Django 3.0.5 on 2020-11-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0070_customexercise_text_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('teacher', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_generalcomment', to='account.Teacher')),
            ],
        ),
    ]
