# Generated by Django 3.0.5 on 2022-12-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0071_auto_20221227_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='is_mark',
            field=models.BooleanField(default=0, verbose_name='Notation ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='mark',
            field=models.PositiveIntegerField(default=0, verbose_name='Sur ?'),
        ),
    ]
