# Generated by Django 3.0.5 on 2020-11-14 11:41

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0071_generalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customanswerbystudent',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=qcm.models.file_directory_student, verbose_name='Fichier pdf ou texte'),
        ),
    ]
