# Generated by Django 3.0.5 on 2020-11-14 16:35

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0072_customanswerbystudent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customanswerbystudent',
            name='imagefile',
        ),
        migrations.CreateModel(
            name='Customanswerimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.file_directory_student, verbose_name='Scan ou image ou Photo')),
                ('customanswerbystudent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='customexercise_custom_answer_image', to='qcm.Customanswerbystudent')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_custom_answer_image', to='account.Student')),
            ],
        ),
    ]
