# Generated by Django 3.0.5 on 2022-12-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0072_auto_20221227_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='mark',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Sur ?'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='situation',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Pour valider le qcm', verbose_name='Nombre minimal de situations'),
        ),
    ]
