# Generated by Django 3.0.5 on 2020-11-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0073_auto_20201114_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customanswerimage',
            name='student',
        ),
    ]
