# Generated by Django 3.0.5 on 2020-11-17 23:29

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('socle', '0004_auto_20201024_2140'),
        ('qcm', '0074_remove_customanswerimage_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanswerimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.file_directory_to_student, verbose_name='Scan ou image ou Photo'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_parcours', to='account.Teacher', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='level',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_parcours', to='socle.Level'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé à partir de'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_parcours', to='account.Teacher'),
        ),
    ]
