# Generated by Django 3.0.5 on 2023-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0074_auto_20230102_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='is_publish',
            field=models.BooleanField(default=0, verbose_name='Publié ?'),
        ),
    ]
