# Generated by Django 3.0.5 on 2023-01-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0075_supportfile_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportfile',
            name='is_publish',
        ),
    ]
