# Generated by Django 3.0.5 on 2020-11-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0075_auto_20201118_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_root',
            field=models.BooleanField(default=0, verbose_name='Groupe de parcours'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='subparcours',
            field=models.ManyToManyField(blank=True, related_name='_parcours_subparcours_+', to='qcm.Parcours', verbose_name='Sous parcours'),
        ),
    ]
