# Generated by Django 3.0.5 on 2020-11-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0076_auto_20201118_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcours',
            old_name='is_root',
            new_name='is_leaf',
        ),
    ]
