# Generated by Django 3.0.5 on 2023-01-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0076_remove_supportfile_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='supportfile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='qcm.Supportfile', verbose_name='Fichier Géogebra'),
        ),
    ]
