# Generated by Django 3.0.5 on 2023-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0077_auto_20230104_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='annoncement',
            field=models.TextField(blank=True, default='', verbose_name='Consigne'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='correction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Corrigé'),
        ),
    ]
