# Generated by Django 3.0.5 on 2020-11-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0077_auto_20201118_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='subparcours',
        ),
        migrations.AddField(
            model_name='parcours',
            name='folder_parcours',
            field=models.ManyToManyField(blank=True, related_name='_parcours_folder_parcours_+', to='qcm.Parcours', verbose_name='Nom de parcours'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_folder',
            field=models.BooleanField(default=0, verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='leaf_parcours',
            field=models.ManyToManyField(blank=True, related_name='_parcours_leaf_parcours_+', to='qcm.Parcours', verbose_name='Nom de parcours'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_leaf',
            field=models.BooleanField(default=0, verbose_name='Sous-parcours'),
        ),
    ]
