# Generated by Django 3.0.5 on 2020-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0078_auto_20201118_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_leaf',
            field=models.BooleanField(default=0, verbose_name='Sous-parcours ?'),
        ),
    ]
