# Generated by Django 3.0.5 on 2023-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0078_auto_20230106_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='nb_pseudo',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de pseudo situation'),
        ),
    ]
