# Generated by Django 3.0.5 on 2020-11-19 21:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0079_auto_20201119_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_lock',
            field=models.BooleanField(default=0, verbose_name='Exercice cloturé ?'),
        ),
        migrations.AddField(
            model_name='supportfile',
            name='correction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Correction'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='annoncement',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Précision sur le savoir faire'),
        ),
    ]
