# Generated by Django 3.0.5 on 2023-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0079_supportfile_nb_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='nb_pseudo',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de pseudo situation'),
        ),
    ]
