# Generated by Django 3.0.5 on 2020-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0080_auto_20201119_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_mark',
            field=models.BooleanField(default=0, verbose_name='Notation ?'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='mark',
            field=models.PositiveIntegerField(default=0, verbose_name='Sur ?'),
        ),
        migrations.AddField(
            model_name='writtenanswerbystudent',
            name='point',
            field=models.CharField(default='', max_length=10, verbose_name='Note'),
        ),
    ]
