# Generated by Django 3.0.5 on 2023-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0080_auto_20230109_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='is_display_correction',
            field=models.BooleanField(default=0, verbose_name='Afficher le corrigé ?'),
        ),
    ]
