# Generated by Django 3.0.5 on 2023-01-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0081_supportfile_is_display_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='is_written',
            field=models.BooleanField(default=0, verbose_name='Mots à écrire ?'),
        ),
    ]
