# Generated by Django 3.0.5 on 2020-11-21 08:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0081_auto_20201119_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='mark',
            field=models.CharField(default='', max_length=3, verbose_name='Sur ?'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='correction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Corrigé'),
        ),
    ]
