# Generated by Django 3.0.5 on 2020-11-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0082_auto_20201121_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_correction_visible',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
