# Generated by Django 3.0.5 on 2023-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0082_supportfile_is_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='subtick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='nb_pseudo',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de pseudo situation'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='tick',
            field=models.FloatField(blank=True, null=True, verbose_name='Unité'),
        ),
    ]
