# Generated by Django 3.0.5 on 2023-01-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0083_auto_20230111_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='score_display',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='tick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation principale'),
        ),
    ]
