# Generated by Django 3.0.5 on 2020-11-28 22:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('qcm', '0083_relationship_is_correction_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exerciselocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code du parcours*')),
                ('is_lock', models.BooleanField(default=0, editable=False)),
                ('custom', models.BooleanField(default=0, editable=False)),
                ('customexercise', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customexercise_exerciselocker', to='qcm.Customexercise')),
                ('relationship', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_exerciselocker', to='qcm.Relationship')),
                ('student', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_exerciselocker', to='account.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
