# Generated by Django 3.0.5 on 2020-11-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0084_exerciselocker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselocker',
            name='is_lock',
        ),
    ]
