# Generated by Django 3.0.5 on 2023-01-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0084_auto_20230113_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='score_display',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
