# Generated by Django 3.0.5 on 2023-01-16 16:03

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0085_auto_20230113_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportchoice',
            name='imageanswer',
            field=models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='supportchoice',
            name='imageanswerbis',
            field=models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Image par paire'),
        ),
        migrations.AlterField(
            model_name='supportsubchoice',
            name='imageanswer',
            field=models.ImageField(blank=True, default='', null=True, upload_to=qcm.models.subchoice_directory_path, verbose_name='Image'),
        ),
    ]
