# Generated by Django 3.0.5 on 2020-11-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0085_remove_exerciselocker_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselocker',
            name='lock',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
