# Generated by Django 3.0.5 on 2023-01-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0086_auto_20230116_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='nb_subpseudo',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de pseudo proposition'),
        ),
    ]
