# Generated by Django 3.0.5 on 2020-12-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0086_exerciselocker_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='relationships_courses', to='qcm.Relationship', verbose_name='Lier ce cours à'),
        ),
        migrations.AlterField(
            model_name='resultggbskill',
            name='relationship',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_resultggbskills', to='qcm.Relationship'),
        ),
    ]
