# Generated by Django 3.0.5 on 2020-12-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0004_auto_20201024_2140'),
        ('qcm', '0086_exerciselocker_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='relationships_courses', to='qcm.Relationship', verbose_name='Lier ce cours à'),
        ),
        migrations.AlterField(
            model_name='resultggbskill',
            name='relationship',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_resultggbskills', to='qcm.Relationship'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supportfiles', to='socle.Knowledge', verbose_name='Savoir faire associé'),
        ),
    ]
