# Generated by Django 3.0.5 on 2020-12-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        ('qcm', '0087_auto_20201212_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='subject',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_parcours', to='socle.Subject', verbose_name='Enseignement'),
        ),
    ]
