# Generated by Django 3.0.5 on 2023-01-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0087_supportfile_nb_subpseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportfile',
            name='canvasimage',
        ),
    ]
