# Generated by Django 3.0.5 on 2020-12-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0088_parcours_subject'),
        ('qcm', '0087_auto_20201213_1424'),
    ]

    operations = [
    ]
