# Generated by Django 3.0.5 on 2023-01-21 18:32

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0089_auto_20230121_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchoice',
            name='audioanswer',
            field=models.FileField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='supportchoice',
            name='audioanswerbis',
            field=models.FileField(blank=True, default='', null=True, upload_to=qcm.models.choice_directory_path, verbose_name='Audio'),
        ),
    ]
