# Generated by Django 3.0.5 on 2020-12-29 18:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0089_merge_20201221_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='exerciselocker',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
    ]
