# Generated by Django 3.0.5 on 2023-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0090_auto_20230121_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportchoice',
            name='is_written',
            field=models.BooleanField(blank=True, default=0, verbose_name='Mots à écrire ?'),
        ),
    ]
