# Generated by Django 3.0.5 on 2021-01-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        ('qcm', '0090_auto_20201229_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='order',
            new_name='ranking',
        ),
        migrations.AlterField(
            model_name='parcours',
            name='level',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_parcours', to='socle.Level'),
        ),
    ]
