# Generated by Django 3.0.5 on 2021-01-12 22:14

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcm', '0091_auto_20210106_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(editable=False, max_length=255)),
                ('style', models.CharField(editable=False, max_length=255)),
                ('attr_id', models.CharField(editable=False, max_length=255)),
                ('content', models.TextField(editable=False)),
                ('document', models.CharField(editable=False, max_length=100)),
                ('document_id', models.PositiveIntegerField(default=3, editable=False)),
                ('report', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='RAS', verbose_name='Remarque*')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_document_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
