# Generated by Django 3.0.5 on 2021-01-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0092_documentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentreport',
            name='attr_id',
        ),
        migrations.RemoveField(
            model_name='documentreport',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='documentreport',
            name='content',
        ),
        migrations.RemoveField(
            model_name='documentreport',
            name='style',
        ),
    ]
