# Generated by Django 3.0.5 on 2021-01-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0093_auto_20210112_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreport',
            name='done',
            field=models.BooleanField(default=0, verbose_name='Fait'),
        ),
    ]
