# Generated by Django 3.0.5 on 2021-01-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0094_documentreport_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentreport',
            old_name='done',
            new_name='is_done',
        ),
    ]
