# Generated by Django 3.0.5 on 2021-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0095_auto_20210113_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='maxexo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre max de réalisation par exercice'),
        ),
    ]
