# Generated by Django 3.0.5 on 2023-05-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0095_auto_20230504_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfile',
            name='is_paper',
            field=models.BooleanField(blank=True, default=1, verbose_name="Nécessite l'utilisation d'une feuille de papier"),
        ),
    ]
