# Generated by Django 3.0.5 on 2021-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0096_parcours_maxexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='maxexo',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
