# Generated by Django 3.0.5 on 2023-06-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0096_auto_20230504_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='codebook',
            field=models.CharField(blank=True, default='', editable=False, max_length=5, verbose_name='Code Livre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='supportfile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='qcm.Supportfile', verbose_name='Enoncé'),
        ),
    ]
