# Generated by Django 3.0.5 on 2023-07-23 15:42

from django.db import migrations, models
import django.db.models.deletion
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_homeworkless_toolless'),
        ('account', '0032_auto_20230605_2102'),
        ('qcm', '0097_auto_20230614_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docperso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du quizz')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=qcm.models.docperso_directory_path, verbose_name='Fichier')),
                ('is_share', models.BooleanField(default=0, verbose_name='Mutualisé ?')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Début de publication')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé dès le')),
                ('folders', models.ManyToManyField(blank=True, related_name='docpersos', to='qcm.Folder')),
                ('groups', models.ManyToManyField(blank=True, related_name='docpersos', to='group.Group')),
                ('parcours', models.ManyToManyField(blank=True, related_name='docpersos', to='qcm.Parcours')),
                ('students', models.ManyToManyField(blank=True, editable=False, related_name='docpersos', to='account.Student')),
                ('teacher', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='docpersos', to='account.Teacher')),
            ],
        ),
    ]
