# Generated by Django 3.0.5 on 2021-01-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0097_relationship_maxexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='maxexo',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Nombre max de réalisation par exercice'),
        ),
    ]
