# Generated by Django 3.0.5 on 2021-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0098_auto_20210127_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='maxexo',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Nombre max de réalisation par exercice'),
        ),
    ]
