# Generated by Django 3.0.5 on 2023-07-23 18:38

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0098_docperso'),
    ]

    operations = [
        migrations.AddField(
            model_name='docperso',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lien externe'),
        ),
        migrations.AlterField(
            model_name='docperso',
            name='file',
            field=models.FileField(blank=True, upload_to=qcm.models.docperso_directory_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='docperso',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de publication'),
        ),
        migrations.AlterField(
            model_name='docperso',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
