# Generated by Django 3.0.5 on 2021-01-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0099_auto_20210127_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselocker',
            name='customexercise',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customexercise_exerciselocker', to='qcm.Customexercise'),
        ),
        migrations.AlterField(
            model_name='exerciselocker',
            name='relationship',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_exerciselocker', to='qcm.Relationship'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='maxexo',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Nombre max de réalisation par exercice'),
        ),
    ]
