# Generated by Django 3.0.5 on 2023-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0099_auto_20230723_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='docperso',
            name='ranking',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
