# Generated by Django 3.0.5 on 2021-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_group_studentprofile'),
        ('qcm', '0100_auto_20210128_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='group_parcours', to='group.Group'),
        ),
    ]
