# Generated by Django 3.0.5 on 2023-08-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('qcm', '0100_docperso_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='docperso',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='docpersos', to='socle.Level'),
        ),
    ]
