# Generated by Django 3.0.5 on 2023-08-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('qcm', '0101_docperso_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='docperso',
            name='subject',
            field=models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='docpersos', to='socle.Subject'),
        ),
    ]
