# Generated by Django 3.0.5 on 2021-02-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0101_parcours_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='exercise',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_relationship', to='qcm.Exercise'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='parcours',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='parcours_relationship', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='resultexercise',
            name='exercise',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results_e', to='qcm.Exercise'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='exercise',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ggbfile_studentanswer', to='qcm.Exercise'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='parcours',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qcm.Parcours'),
        ),
        migrations.AlterField(
            model_name='writtenanswerbystudent',
            name='relationship',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_written_answer', to='qcm.Relationship'),
        ),
    ]
