# Generated by Django 3.0.5 on 2021-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0102_auto_20210217_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportfile',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
