# Generated by Django 3.0.5 on 2023-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0102_docperso_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='docperso',
            name='is_archive',
            field=models.BooleanField(default=0, verbose_name='Archive ?'),
        ),
    ]
