# Generated by Django 3.0.5 on 2023-09-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0103_docperso_is_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docperso',
            name='folders',
            field=models.ManyToManyField(blank=True, editable=False, related_name='docpersos', to='qcm.Folder'),
        ),
        migrations.AlterField(
            model_name='docperso',
            name='parcours',
            field=models.ManyToManyField(blank=True, editable=False, related_name='docpersos', to='qcm.Parcours'),
        ),
    ]
