# Generated by Django 3.0.5 on 2021-02-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0103_supportfile_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_achievement',
            field=models.BooleanField(default=0, verbose_name='Avancement ?'),
        ),
    ]
