# Generated by Django 3.0.5 on 2023-09-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0104_auto_20230925_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docperso',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='docpersos', to='qcm.Folder'),
        ),
        migrations.AlterField(
            model_name='docperso',
            name='parcours',
            field=models.ManyToManyField(blank=True, related_name='docpersos', to='qcm.Parcours'),
        ),
    ]
