# Generated by Django 3.0.5 on 2021-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0104_parcours_is_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_reading',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
