# Generated by Django 3.0.5 on 2021-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0105_studentanswer_is_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='is_realtime',
            field=models.BooleanField(default=0, verbose_name='Temps réel ?'),
        ),
        migrations.AlterField(
            model_name='customexercise',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée (min.)'),
        ),
        migrations.AlterField(
            model_name='customexercise',
            name='lock',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé dès le'),
        ),
    ]
