# Generated by Django 3.0.5 on 2023-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0105_auto_20230926_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='type_i',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
