# Generated by Django 3.0.5 on 2021-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0106_auto_20210226_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='customanswerimage',
            name='imagecanvas',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
