# Generated by Django 3.0.5 on 2023-10-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0107_auto_20231010_1747'),
        ('qcm', '0106_relationship_type_i'),
    ]

    operations = [
    ]
