# Generated by Django 3.0.5 on 2021-03-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0107_customanswerimage_imagecanvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='zoom',
            field=models.BooleanField(default=1, editable=False),
        ),
    ]
