# Generated by Django 3.0.5 on 2021-03-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0108_parcours_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='zoom',
            field=models.BooleanField(default=1, verbose_name='Zoom'),
        ),
    ]
