# Generated by Django 3.0.5 on 2023-10-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0108_merge_20231011_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='type_i',
        ),
    ]
