# Generated by Django 3.0.5 on 2021-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0109_auto_20210305_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='zoom',
            field=models.BooleanField(default=1, verbose_name='Zoom ?'),
        ),
    ]
