# Generated by Django 3.0.5 on 2023-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0110_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='percent',
            name='bibliotex',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='percent',
            name='cours',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='percent',
            name='docperso',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='percent',
            name='flashpack',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='percent',
            name='qflash',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False),
        ),
        migrations.AddField(
            model_name='percent',
            name='quizz',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False),
        ),
    ]
