# Generated by Django 3.0.5 on 2021-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0110_auto_20210306_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='A partir de'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillage'),
        ),
    ]
