# Generated by Django 3.0.5 on 2023-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0111_auto_20231015_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='percent',
            name='today',
            field=models.DateField(auto_now=True),
        ),
    ]
