# Generated by Django 3.0.5 on 2021-03-21 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_is_board'),
        ('qcm', '0111_auto_20210314_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tracker', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('path', models.CharField(editable=False, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.PositiveIntegerField(default=0, editable=False)),
                ('is_custom', models.BooleanField(default=0)),
                ('parcours', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='qcm.Parcours')),
            ],
        ),
    ]
