# Generated by Django 3.0.5 on 2021-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0112_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
