# Generated by Django 3.0.5 on 2021-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0113_auto_20210321_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='path',
        ),
    ]
