# Generated by Django 3.0.5 on 2023-10-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0113_parcours_is_display_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcours',
            old_name='is_display_relation',
            new_name='is_full_display',
        ),
    ]
