# Generated by Django 3.0.5 on 2021-03-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0114_remove_tracker_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='exercise_id',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='is_custom',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
