# Generated by Django 3.0.5 on 2021-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0115_auto_20210321_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='exercise_id',
            field=models.PositiveIntegerField(default=0, editable=False, null=True),
        ),
    ]
