# Generated by Django 3.0.5 on 2021-03-21 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcm', '0116_auto_20210321_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tracker', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
