# Generated by Django 3.0.5 on 2021-03-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0117_auto_20210321_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
