# Generated by Django 3.0.5 on 2021-03-21 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qcm', '0118_delete_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.PositiveIntegerField(default=0, editable=False, null=True)),
                ('is_custom', models.BooleanField(blank=True, default=0)),
                ('parcours', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='qcm.Parcours')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
