# Generated by Django 3.0.5 on 2021-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0119_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_next',
            field=models.BooleanField(default=0, verbose_name='Suivant ?'),
        ),
    ]
