# Generated by Django 3.0.5 on 2021-04-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0120_parcours_is_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='maxexo',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Tentatives'),
        ),
    ]
