# Generated by Django 3.0.5 on 2021-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0121_auto_20210405_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_back',
            field=models.BooleanField(default=0, verbose_name='Précédent ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_exit',
            field=models.BooleanField(default=0, verbose_name='Sortie ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_shuffle',
            field=models.BooleanField(default=0, verbose_name='Ordre aléatoire ?'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='is_start',
            field=models.BooleanField(default=0, verbose_name='Démarrage initial ?'),
        ),
    ]
