# Generated by Django 3.0.5 on 2021-04-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0122_auto_20210407_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='is_back',
        ),
    ]
