# Generated by Django 3.0.5 on 2021-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0123_remove_parcours_is_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcours',
            name='is_shuffle',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='is_start',
        ),
        migrations.AlterField(
            model_name='parcours',
            name='is_exit',
            field=models.BooleanField(default=0, verbose_name='Retour aux exercices ?'),
        ),
    ]
