# Generated by Django 3.0.5 on 2021-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0124_auto_20210407_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
