# Generated by Django 3.0.5 on 2021-04-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210410_1553'),
        ('qcm', '0125_exercise_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_course', to='account.Teacher'),
        ),
    ]
