# Generated by Django 3.0.5 on 2021-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0126_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='is_stop',
            field=models.BooleanField(default=0, verbose_name='Dépassement ?'),
        ),
    ]
