# Generated by Django 3.0.5 on 2021-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0127_parcours_is_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_stop',
            field=models.BooleanField(default=0, verbose_name='Limité ?'),
        ),
    ]
