# Generated by Django 3.0.5 on 2021-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0128_auto_20210415_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcours',
            name='is_leaf',
            field=models.BooleanField(default=0, verbose_name='Inclus dans un dossier ?'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='leaf_parcours',
            field=models.ManyToManyField(blank=True, related_name='_parcours_leaf_parcours_+', to='qcm.Parcours', verbose_name='Nom du dossier'),
        ),
    ]
