# Generated by Django 3.0.5 on 2021-06-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210411_1355'),
        ('qcm', '0129_auto_20210426_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastering_done',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='students_mastering_done', to='account.Student'),
        ),
        migrations.AlterField(
            model_name='masteringcustom_done',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='students_mastering_custom_done', to='account.Student'),
        ),
    ]
