# Generated by Django 2.1.2 on 2020-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuseau hoaire'),
        ),
    ]
