# Generated by Django 3.0.5 on 2020-06-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_sacado', '0002_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
