# Generated by Django 3.0.5 on 2020-06-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('account', '0003_user_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_id',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='school.School'),
        ),
    ]
