# Generated by Django 2.1.2 on 2020-04-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200413_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time_zome',
            new_name='time_zone',
        ),
    ]
