# Generated by Django 3.0.5 on 2020-07-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_sacado', '0005_auto_20200612_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
