# Generated by Django 3.0.5 on 2020-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200612_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgu',
            field=models.BooleanField(default=0),
        ),
    ]
