# Generated by Django 3.0.5 on 2020-04-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('account', '0006_auto_20200416_2127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultknowledge',
            unique_together={('student', 'knowledge')},
        ),
    ]
