# Generated by Django 3.0.5 on 2020-04-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('account', '0007_auto_20200420_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultknowledge',
            name='knowledge',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_resultknowledge', to='socle.Knowledge'),
        ),
        migrations.AlterField(
            model_name='resultknowledge',
            name='student',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultknowledge', to='account.Student'),
        ),
    ]
