# Generated by Django 3.0.5 on 2020-07-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200614_0937'),
        ('socle', '0002_auto_20200723_0115'),
        ('account', '0007_auto_20200713_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='teacher', to='socle.Subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='school.School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Élève'), (1, 'Parent'), (2, 'Enseignant')], editable=False, null=True),
        ),
    ]
