# Generated by Django 3.0.5 on 2020-05-03 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200425_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('task_post', models.BooleanField(default=1, verbose_name='Notification de tache ?')),
                ('students', models.ManyToManyField(editable=False, related_name='students_parent', to='account.Student')),
            ],
        ),
    ]
