# Generated by Django 3.0.5 on 2020-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0003_subject_shortname'),
        ('account', '0008_auto_20200723_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teacher', to='socle.Subject', verbose_name='Enseignements'),
        ),
    ]
