# Generated by Django 3.0.5 on 2020-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200504_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_authorized',
            field=models.BooleanField(default=0, editable=0),
        ),
    ]
