# Generated by Django 3.0.5 on 2020-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_teacher_is_authorized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_authorized',
        ),
        migrations.AddField(
            model_name='user',
            name='is_extra',
            field=models.BooleanField(default=0, editable=0),
        ),
    ]
