# Generated by Django 3.0.5 on 2020-07-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200723_1000'),
        ('account', '0011_auto_20200726_2017'),
    ]

    operations = [
    ]
