# Generated by Django 3.0.5 on 2020-05-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('account', '0012_auto_20200504_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='skill_resultskill', to='socle.Skill')),
                ('student', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultskill', to='account.Student')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
