# Generated by Django 3.0.5 on 2020-09-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20200727_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_extra',
            field=models.BooleanField(default=0),
        ),
    ]
