# Generated by Django 3.0.5 on 2020-05-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('account', '0013_resultskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultskill',
            name='skill',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultskill', to='socle.Skill'),
        ),
        migrations.CreateModel(
            name='Resultskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='skill_resultskills', to='socle.Skill')),
                ('student', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultskills', to='account.Student')),
            ],
        ),
    ]
