# Generated by Django 3.0.5 on 2020-12-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_mailing',
            field=models.BooleanField(default=1, verbose_name='Réception de messages ?'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='exercise_post',
            field=models.BooleanField(default=1, verbose_name="Réception de notification de création d'exercice ?"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='notification',
            field=models.BooleanField(default=1, verbose_name='Réception de notifications ?'),
        ),
    ]
