# Generated by Django 3.0.5 on 2020-05-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('account', '0014_auto_20200517_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultlastskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultskill', to='socle.Skill')),
                ('student', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultskill', to='account.Student')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.AlterField(
            model_name='resultskill',
            name='skill',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='skill_resultskills', to='socle.Skill'),
        ),
        migrations.AlterField(
            model_name='resultskill',
            name='student',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_resultskills', to='account.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='resultskill',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Resultskills',
        ),
    ]
