# Generated by Django 3.0.5 on 2020-12-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20201215_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cgu',
            field=models.BooleanField(default=1),
        ),
    ]
