# Generated by Django 3.0.5 on 2020-12-29 18:08

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20201229_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closure',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Date de fin d'adhésion"),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('file', models.FileField(blank=True, default='', editable=False, null=True, upload_to=account.models.file_directory_path, verbose_name='facture')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
