# Generated by Django 3.0.5 on 2020-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200517_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
    ]
