# Generated by Django 3.0.5 on 2020-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, unique=True),
        ),
    ]
