# Generated by Django 3.0.5 on 2020-12-29 18:22

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20201229_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('file', models.FileField(blank=True, default='', editable=False, null=True, upload_to=account.models.file_directory_path, verbose_name='fichier')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='Date de fin')),
                ('amont', models.CharField(editable=False, max_length=10, verbose_name='Montant')),
                ('menu', models.CharField(editable=False, max_length=50, verbose_name='Menu')),
                ('children', models.PositiveIntegerField(default=1, editable=False, verbose_name='Nb enfant')),
                ('duration', models.PositiveIntegerField(default=1, editable=False, verbose_name="Durée de l'adhésion")),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
