# Generated by Django 3.0.5 on 2020-05-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200518_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
    ]
