# Generated by Django 3.0.5 on 2020-12-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20201229_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhesion',
            old_name='amont',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='date_end',
            field=models.DateTimeField(editable=False, verbose_name='Date de fin'),
        ),
    ]
