# Generated by Django 3.0.5 on 2020-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20201229_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='code',
            field=models.CharField(editable=False, max_length=50, verbose_name='Code'),
        ),
    ]
