# Generated by Django 3.0.5 on 2021-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_code_acad'),
        ('account', '0019_auto_20201230_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(related_name='schools_to_users', to='school.School', verbose_name='Autres établissement à administrer'),
        ),
    ]
