# Generated by Django 3.0.5 on 2020-05-24 14:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200518_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code du parcours*'),
        ),
    ]
