# Generated by Django 3.0.5 on 2020-05-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
        ('account', '0020_auto_20200524_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultknowledge',
            name='knowledge',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results_k', to='socle.Knowledge'),
        ),
        migrations.AlterField(
            model_name='resultknowledge',
            name='student',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results_k', to='account.Student'),
        ),
    ]
