# Generated by Django 3.0.5 on 2021-01-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_code_acad'),
        ('account', '0020_user_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='schools_to_users', to='school.School', verbose_name='Autres établissement à administrer'),
        ),
    ]
