# Generated by Django 3.0.5 on 2020-05-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0003_auto_20200528_2116'),
        ('account', '0021_auto_20200528_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultskill',
            name='skill',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results_s', to='socle.Skill'),
        ),
        migrations.AlterField(
            model_name='resultskill',
            name='student',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results_s', to='account.Student'),
        ),
    ]
