# Generated by Django 3.0.5 on 2021-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20210111_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_testeur',
            field=models.BooleanField(default=0),
        ),
    ]
