# Generated by Django 3.0.5 on 2021-01-27 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_code_acad'),
        ('account', '0022_user_is_testeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='school.Country'),
        ),
    ]
