# Generated by Django 3.0.5 on 2021-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_board',
            field=models.BooleanField(default=0),
        ),
    ]
