# Generated by Django 3.0.5 on 2022-08-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('account', '0025_auto_20220731_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='levels_to_group', to='socle.Level', verbose_name='Niveaux souhaités'),
        ),
    ]
