# Generated by Django 3.0.5 on 2021-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210410_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='exercise_post',
            field=models.BooleanField(default=0, verbose_name="Réception de notification de création d'exercice ?"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_mailing',
            field=models.BooleanField(default=0, verbose_name='Réception de messages ?'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='notification',
            field=models.BooleanField(default=0, verbose_name='Réception de notifications ?'),
        ),
    ]
