# Generated by Django 3.0.5 on 2022-09-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_subject_is_active'),
        ('account', '0026_auto_20220803_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_student', to='socle.Level', verbose_name='Niveau'),
        ),
    ]
