# Generated by Django 3.0.5 on 2022-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_teacher_is_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, default='default', editable=False, max_length=10),
        ),
    ]
