# Generated by Django 3.0.5 on 2022-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_user_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nb', models.PositiveIntegerField()),
            ],
        ),
    ]
