# Generated by Django 3.0.5 on 2023-06-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_homeworkless_toolless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolless',
            name='student',
        ),
        migrations.DeleteModel(
            name='Homeworkless',
        ),
        migrations.DeleteModel(
            name='Toolless',
        ),
    ]
