# Generated by Django 3.0.5 on 2021-11-11 15:23

from django.db import migrations, models
import django.db.models.deletion
import flashcard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socle', '0006_auto_20211006_2229'),
        ('account', '0010_remove_user_gar_token'),
        ('group', '0004_auto_20210919_1915'),
        ('qcm', '0021_auto_20211027_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answercard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0, editable=False)),
                ('is_correct', models.BooleanField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flashpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du flashpack')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#5d4391', max_length=255, verbose_name='Couleur')),
                ('vignette', models.ImageField(blank=True, default='', null=True, upload_to=flashcard.models.flashpack_directory_path, verbose_name="Vignette d'accueil")),
                ('is_share', models.BooleanField(default=0, verbose_name='Mutualisé ?')),
                ('is_archive', models.BooleanField(default=0, verbose_name='Archivé ?')),
                ('interslide', models.PositiveIntegerField(blank=True, default=10, verbose_name='Temps entre les questions')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Début de publication')),
                ('stop', models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé dès le')),
                ('folders', models.ManyToManyField(blank=True, related_name='flashpacks', to='qcm.Folder')),
                ('groups', models.ManyToManyField(blank=True, related_name='flashpacks', to='group.Group')),
                ('levels', models.ManyToManyField(blank=True, related_name='flashpacks', to='socle.Level')),
                ('parcours', models.ManyToManyField(blank=True, related_name='flashpacks', to='qcm.Parcours')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashpacks', to='socle.Subject')),
                ('teacher', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='flashpacks', to='account.Teacher')),
                ('themes', models.ManyToManyField(blank=True, related_name='flashpacks', to='socle.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Titre')),
                ('question', models.TextField(blank=True, default='', max_length=255, verbose_name='Question écrite')),
                ('calculator', models.BooleanField(default=0, verbose_name='Calculatrice ?')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse attendu')),
                ('size', models.PositiveIntegerField(choices=[(16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56')], default=32, verbose_name='Taille de police')),
                ('imagefile', models.ImageField(blank=True, default='', upload_to=flashcard.models.flashcard_directory_path, verbose_name='Image')),
                ('audio', models.FileField(blank=True, default='', upload_to=flashcard.models.flashcard_directory_path, verbose_name='Audio')),
                ('video', models.TextField(blank=True, default='', verbose_name='Vidéo intégrée')),
                ('duration', models.PositiveIntegerField(blank=True, default=20, verbose_name='Durée')),
                ('levels', models.ManyToManyField(blank=True, related_name='flashcards', to='socle.Level')),
                ('students', models.ManyToManyField(blank=True, editable=False, related_name='flashcards', through='flashcard.Answercard', to='account.Student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='socle.Subject')),
                ('theme', models.ManyToManyField(blank=True, related_name='flashcards', to='socle.Theme')),
                ('waiting', models.ManyToManyField(blank=True, related_name='flashcards', to='socle.Waiting')),
            ],
        ),
        migrations.AddField(
            model_name='answercard',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answercards', to='flashcard.Flashcard'),
        ),
        migrations.AddField(
            model_name='answercard',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answercards', to='account.Student'),
        ),
    ]
