# Generated by Django 3.0.5 on 2021-11-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpack',
            name='is_publish',
            field=models.BooleanField(default=1, verbose_name='Publié ?'),
        ),
    ]
