# Generated by Django 3.0.5 on 2021-11-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_flashpack_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpack',
            name='flashcards',
            field=models.ManyToManyField(blank=True, related_name='flashpacks', to='flashcard.Flashcard'),
        ),
    ]
