# Generated by Django 3.0.5 on 2021-11-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashpack_flashcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpack',
            name='is_favorite',
            field=models.BooleanField(default=0, verbose_name='Favori ?'),
        ),
    ]
