# Generated by Django 3.0.5 on 2021-11-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_flashpack_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashpack',
            name='is_favorite',
            field=models.BooleanField(default=1, verbose_name='Favori ?'),
        ),
    ]
