# Generated by Django 3.0.5 on 2021-11-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_auto_20211112_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='helper',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide proposée'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(default='', max_length=255, verbose_name='Réponse attendu'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(default='', max_length=255, verbose_name='Question écrite'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='title',
            field=models.TextField(default='', max_length=255, verbose_name='Titre'),
        ),
    ]
