# Generated by Django 3.0.5 on 2021-11-13 06:02

from django.db import migrations, models
import flashcard.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_auto_20211113_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='audioanswer',
            field=models.FileField(blank=True, default='', upload_to=flashcard.models.flashcard_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='audiohelper',
            field=models.FileField(blank=True, default='', upload_to=flashcard.models.flashcard_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='imagefileanswer',
            field=models.ImageField(blank=True, default='', upload_to=flashcard.models.flashcard_directory_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='imagefilehelper',
            field=models.ImageField(blank=True, default='', upload_to=flashcard.models.flashcard_directory_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='videoanswer',
            field=models.TextField(blank=True, default='', verbose_name='Vidéo intégrée'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='videohelper',
            field=models.TextField(blank=True, default='', verbose_name='Vidéo intégrée'),
        ),
    ]
