# Generated by Django 3.0.5 on 2023-09-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0104_auto_20230925_2213'),
        ('flashcard', '0029_auto_20220204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashpack',
            name='folders',
            field=models.ManyToManyField(blank=True, editable=False, related_name='flashpacks', to='qcm.Folder'),
        ),
        migrations.AlterField(
            model_name='flashpack',
            name='parcours',
            field=models.ManyToManyField(blank=True, editable=False, related_name='flashpacks', to='qcm.Parcours'),
        ),
    ]
