# Generated by Django 3.0.5 on 2023-09-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0031_auto_20230926_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpack',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
