# Generated by Django 3.0.5 on 2020-06-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('town', models.CharField(default='', max_length=255, verbose_name='ville')),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='school', related_query_name='school', to='school.Country', verbose_name='Pays')),
            ],
        ),
    ]
