# Generated by Django 3.0.5 on 2020-06-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='school', related_query_name='school', to='school.Country', verbose_name='Pays'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.PositiveIntegerField(default=50, verbose_name='Seuil 1 : NA à ECA')),
                ('medium', models.PositiveIntegerField(default=70, verbose_name='Seuil 2 : ACE à acquis')),
                ('up', models.PositiveIntegerField(default=85, verbose_name='Seuil 3 : acquis à dépassé')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='aptitude', to='school.School')),
            ],
        ),
    ]
