# Generated by Django 3.0.5 on 2021-01-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200614_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code_acad',
            field=models.CharField(default='', max_length=255, verbose_name='Code académique'),
        ),
    ]
