# Generated by Django 3.0.5 on 2021-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_code_acad'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='school',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse"),
        ),
    ]
