# Generated by Django 3.0.5 on 2021-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210307_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='get_seconde_to_comp',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
