# Generated by Django 3.0.5 on 2021-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_get_seconde_to_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='school',
            name='nbstudents',
            field=models.PositiveIntegerField(blank=True, default=500, verbose_name="Nombre d'élèves"),
        ),
    ]
