# Generated by Django 3.0.5 on 2022-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210904_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='school',
            name='resiliation',
            field=models.TextField(blank=True, default='', verbose_name='Motif de Résiliation'),
        ),
    ]
