# Generated by Django 3.0.5 on 2021-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210410_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='nbstudents',
            field=models.PositiveIntegerField(default=500, verbose_name="Nombre d'élèves"),
        ),
    ]
