# Generated by Django 3.0.5 on 2022-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20220804_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tiers',
            field=models.PositiveIntegerField(default=411, editable=False),
        ),
    ]
