# Generated by Django 3.0.5 on 2021-04-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210410_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='school',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='aptitude', to='school.School'),
        ),
    ]
