# Generated by Django 3.0.5 on 2022-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_town'),
    ]

    operations = [

    ]
