# Generated by Django 3.0.5 on 2022-08-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='address',
        ),
        migrations.RemoveField(
            model_name='town',
            name='code_acad',
        ),
        migrations.RemoveField(
            model_name='town',
            name='complement',
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='school',
            name='code_acad',
            field=models.CharField(default='999efe', max_length=255, verbose_name='Code UAI'),
        ),
        migrations.AddField(
            model_name='school',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse"),
        ),
    ]
