# Generated by Django 3.0.5 on 2021-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20210418_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code_acad',
            field=models.CharField(blank=True, default='999efe', max_length=255, verbose_name='Code académique'),
        ),
    ]
