# Generated by Django 3.0.5 on 2022-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20220809_1325'),
    ]

    operations = [

    ]
