# Generated by Django 3.0.5 on 2022-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20220809_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_primaire',
            field=models.BooleanField(default=1, editable=False),
        ),
    ]
