# Generated by Django 3.0.5 on 2022-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_school_is_primaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_managing',
            field=models.BooleanField(default=1, editable=False),
        ),
    ]
