# Generated by Django 3.0.5 on 2022-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20220809_1326'),
    ]

    operations = [

    ]
