# Generated by Django 3.0.5 on 2022-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_school_is_managing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_managing',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
