# Generated by Django 3.0.5 on 2021-04-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210418_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code_acad',
            field=models.CharField(default='999efe', max_length=255, verbose_name='Code UAI'),
        ),
    ]
