# Generated by Django 3.0.5 on 2021-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210423_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='zip_code',
            field=models.CharField(blank=True, default='99999', max_length=255, verbose_name='Code postal'),
        ),
    ]
