# Generated by Django 3.0.5 on 2021-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_school_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gar',
            field=models.BooleanField(default=0, verbose_name='Connexion via le GAR'),
        ),
    ]
