# Generated by Django 3.0.5 on 2023-10-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20231005_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_managing',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
