# Generated by Django 3.0.5 on 2021-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_school_gar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='gar',
            field=models.BooleanField(default=0, verbose_name='Connexion via le GAR souhaitée'),
        ),
    ]
