# Generated by Django 3.0.5 on 2020-06-01 10:52

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socle', '0001_initial'),
        ('qcm', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code du parcours*')),
                ('name', models.CharField(max_length=255, verbose_name='Nom*')),
                ('color', models.CharField(default='#46119c', max_length=255, verbose_name='Couleur*')),
                ('assign', models.BooleanField(default=1)),
                ('suiviparent', models.BooleanField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_to_group', to='socle.Level', verbose_name='Niveau*')),
                ('parcours', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parcours_group', to='qcm.Parcours')),
                ('students', models.ManyToManyField(blank=True, related_name='students_to_group', to='account.Student', verbose_name='Élèves*')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_to_group', to='account.Teacher', verbose_name='Enseignant*')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
