# Generated by Django 3.0.5 on 2020-06-13 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0006_auto_20200611_1834'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parcours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours_group', to='qcm.Parcours'),
        ),
    ]
