# Generated by Django 3.0.5 on 2020-04-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('qcm', '0016_auto_20200423_2301'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_to_group', to='socle.Level', verbose_name='Niveau*'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parcours',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parcours_group', to='qcm.Parcours'),
        ),
    ]
