# Generated by Django 3.0.5 on 2020-04-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('group', '0002_auto_20200425_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_to_group', to='socle.Level', verbose_name='Niveau*'),
        ),
    ]
