# Generated by Django 3.0.5 on 2020-06-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200613_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parcours',
        ),
    ]
