# Generated by Django 3.0.5 on 2020-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200428_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='suiviparent',
            field=models.BooleanField(default=0),
        ),
    ]
