# Generated by Django 3.0.5 on 2020-06-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_sacado', '0005_auto_20200612_2212'),
        ('group', '0003_remove_group_parcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='account.Teacher', verbose_name='Enseignant*'),
        ),
    ]
