# Generated by Django 3.0.5 on 2020-06-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
        ('group', '0004_auto_20200625_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='socle.Level', verbose_name='Niveau*'),
        ),
    ]
