# Generated by Django 3.0.5 on 2020-05-24 14:10

from django.db import migrations, models
import qcm.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_suiviparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, default=qcm.models.generate_code, max_length=100, unique=True, verbose_name='Code du parcours*'),
        ),
    ]
