# Generated by Django 3.0.5 on 2022-09-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_subject_is_active'),
        ('group', '0004_auto_20210919_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='socle.Level', verbose_name='Niveau*'),
        ),
    ]
