# Generated by Django 3.0.5 on 2022-10-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20220902_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_gar',
            field=models.BooleanField(default=0),
        ),
    ]
