# Generated by Django 3.0.5 on 2020-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20200625_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(blank=True, default='#46119c', max_length=255, null=True, verbose_name='Couleur*'),
        ),
    ]
