# Generated by Django 3.0.5 on 2020-09-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20200710_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lock',
            field=models.BooleanField(default=0),
        ),
    ]
