# Generated by Django 3.0.5 on 2020-10-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('group', '0007_group_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reader', models.BooleanField(default=0)),
                ('is_publisher', models.BooleanField(default=0)),
                ('group', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_sharingteacher', to='group.Group')),
                ('teacher', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_sharingteacher', to='account.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teacher_group', through='group.Sharing_group', to='account.Teacher'),
        ),
    ]
