# Generated by Django 3.0.5 on 2023-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_group_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='recuperation',
            field=models.BooleanField(default=1),
        ),
    ]
