# Generated by Django 3.0.5 on 2020-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200930_1741'),
        ('group', '0008_auto_20201003_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(editable=False, related_name='teacher_group', through='group.Sharing_group', to='account.Teacher'),
        ),
    ]
