# Generated by Django 3.0.5 on 2023-08-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20230605_2102'),
        ('group', '0009_homeworkless_toolless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing_group',
            name='group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_sharingteacher', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='sharing_group',
            name='teacher',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sharingteacher', to='account.Teacher'),
        ),
    ]
