# Generated by Django 3.0.5 on 2023-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_group_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='labelname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de substitution'),
        ),
    ]
