# Generated by Django 3.0.5 on 2020-10-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20201003_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharing_group',
            old_name='is_publisher',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='sharing_group',
            name='is_reader',
        ),
    ]
