# Generated by Django 3.0.5 on 2023-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_group_labelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='labelname',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='Nom de substitution'),
        ),
    ]
