# Generated by Django 3.0.5 on 2020-10-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0003_subject_shortname'),
        ('group', '0012_auto_20201004_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_group', to='socle.Subject', verbose_name='Matière*'),
        ),
    ]
