# Generated by Django 3.0.5 on 2020-12-29 18:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_group_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
    ]
