# Generated by Django 3.0.5 on 2023-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_auto_20230928_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom*'),
        ),
    ]
