# Generated by Django 3.0.5 on 2021-02-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20201229_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='studentprofile',
            field=models.BooleanField(default=0),
        ),
    ]
