# Generated by Django 3.0.5 on 2021-01-09 18:21

import account.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('actif', 'membre actif'), ('honneur', "membre d'honneur"), ('bienfaiteur', 'membre bienfaiteur'), ('bénéficiaire', 'membre bénéficiaire')], default='', max_length=255, verbose_name='Qualité')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=0, editable=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nom')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Prénom')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Email')),
                ('observation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Remarque')),
                ('user', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated', to=settings.AUTH_USER_MODEL, verbose_name='Membre inscrit')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(default=0, verbose_name='vote')),
                ('justification', models.CharField(blank=True, default='', max_length=255, verbose_name='justification (facultatif)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('associated', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='association.Associated')),
                ('user', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='votant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('is_credit', models.BooleanField(default=0)),
                ('objet', models.CharField(max_length=255, verbose_name='Objet*')),
                ('beneficiaire', models.CharField(max_length=255, verbose_name='Bénéficiaire*')),
                ('observation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Observation')),
                ('acting', models.DateTimeField(blank=True, null=True, verbose_name="Date d'effet")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='accontings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
