# Generated by Django 3.0.5 on 2021-01-09 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0002_auto_20210109_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Associated',
            new_name='Associate',
        ),
    ]
