# Generated by Django 3.0.5 on 2021-01-09 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0003_auto_20210109_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='associated',
            new_name='associate',
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('associate', 'user')},
        ),
    ]
