# Generated by Django 3.0.5 on 2021-01-14 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Titre')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='association.Section', verbose_name='Section'),
        ),
    ]
