# Generated by Django 3.0.5 on 2021-07-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_auto_20210727_1136'),
        ('association', '0006_auto_20210725_1703'),
    ]

    operations = [
    ]
