# Generated by Django 3.0.5 on 2021-03-07 14:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_code_acad'),
        ('association', '0006_auto_20210114_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='accounting',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accontings', to='school.Country', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accontings', to='school.School', verbose_name='Etablissement'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='town',
            field=models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='beneficiaire',
            field=models.CharField(blank=True, max_length=255, verbose_name='En faveur de'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accontings', to='association.Accounting', verbose_name='Pays')),
            ],
        ),
    ]
