# Generated by Django 3.0.5 on 2021-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_auto_20210307_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
