# Generated by Django 3.0.5 on 2021-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_auto_20210307_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
