# Generated by Django 3.0.5 on 2021-03-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_auto_20210307_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accontings', to='association.Accounting', verbose_name='Pays'),
        ),
    ]
