# Generated by Django 3.0.5 on 2022-08-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_auto_20210906_1003'),
        ('association', '0007_merge_20210727_1540'),
    ]

    operations = [
    ]
