# Generated by Django 3.0.5 on 2021-03-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210307_1936'),
        ('association', '0010_auto_20210307_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accontings', to='school.Country', verbose_name='Pays'),
        ),
    ]
