# Generated by Django 3.0.5 on 2021-09-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_merge_20210727_1540'),
        ('association', '0010_auto_20210906_1003'),
    ]

    operations = [
    ]
