# Generated by Django 3.0.5 on 2022-08-09 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0009_auto_20220809_1446'),
        ('association', '0011_merge_20220809_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='is_facturation',
            field=models.BooleanField(default=0, verbose_name="Affiche la facture sur l'interface client ?"),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountings', to='school.Country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_abonnement',
            field=models.BooleanField(default=0, verbose_name='Abonnement ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Actif ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_credit',
            field=models.BooleanField(default=0, verbose_name='is_credit ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_paypal',
            field=models.BooleanField(default=0, verbose_name='is_paypal ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='mode',
            field=models.CharField(blank=True, choices=[('Période de test', "Période d'essai"), ('par carte de crédit', 'Carte de crédit'), ('par virement bancaire', 'Virement bancaire'), ('en espèces', 'Espèces'), ('par mandatement administratif', 'Mandatement administratif')], default='', max_length=255, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='plan',
            field=models.ForeignKey(blank=True, default=17, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountings', to='association.Plancomptable', verbose_name='Plan comptable'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountings', to='school.School', verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activeyear',
            name='year',
            field=models.PositiveIntegerField(choices=[(2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026'), (2026, '2026-2027'), (2027, '2027-2028'), (2028, '2028-2029'), (2029, '2029-2030'), (2030, '2030-2031'), (2031, '2031-2032'), (2032, '2032-2033'), (2033, '2033-2034'), (2034, '2034-2035'), (2035, '2035-2036'), (2036, '2036-2037'), (2037, '2037-2038'), (2038, '2038-2039'), (2039, '2039-2040'), (2040, '2040-2041')], default=2021, verbose_name="Année de l'exercice"),
        ),
 
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('town', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Téléphone')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Perdu'), (1, 'En suspens'), (2, 'Paiement en attente'), (3, 'Abonné')], default=3)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='school.Country', verbose_name='Pays')),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='school.School')),
            ],
        ),
 
    ]
