# Generated by Django 3.0.5 on 2021-09-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0011_auto_20210907_1916'),
        ('association', '0011_merge_20210906_1140'),
    ]

    operations = [
    ]
