# Generated by Django 3.0.5 on 2021-09-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_auto_20210914_2058'),
        ('association', '0012_merge_20210910_0017'),
    ]

    operations = [
    ]
