# Generated by Django 3.0.5 on 2021-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_auto_20210308_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Tarif')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Réduction')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name="Nombre d'élèves")),
                ('year', models.CharField(default='', max_length=255, verbose_name='Année')),
                ('is_active', models.BooleanField(default=0, editable=False)),
            ],
        ),
    ]
