# Generated by Django 3.0.5 on 2021-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Année active'),
        ),
    ]
