# Generated by Django 3.0.5 on 2022-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_accountancy_bank_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='idex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Perdu'), (1, 'En suspens'), (2, 'Paiement en attente'), (3, 'Abonné')], default=3),
        ),
    ]
