# Generated by Django 3.0.5 on 2021-04-10 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210410_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0014_auto_20210314_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accontings', to='school.Country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accontings', to=settings.AUTH_USER_MODEL),
        ),
    ]
