# Generated by Django 3.0.5 on 2021-09-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_auto_20210914_2235'),
        ('association', '0014_auto_20210916_1115'),
    ]

    operations = [
    ]
