# Generated by Django 3.0.5 on 2021-04-23 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210423_0528'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0015_auto_20210410_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(editable=False, verbose_name='Date de début')),
                ('date_stop', models.DateTimeField(editable=False, verbose_name='Date de fin')),
                ('accounting', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='association.Accounting')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='school.School')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
