# Generated by Django 3.0.5 on 2022-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_auto_20220804_0001'),
        ('association', '0015_merge_20210916_1430'),
    ]

    operations = [
    ]
