# Generated by Django 3.0.5 on 2022-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_auto_20220804_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='is_cpca',
            field=models.BooleanField(default=0, verbose_name="Produits constatés d'avance ?"),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_abonnement',
            field=models.BooleanField(default=0, verbose_name='Abonnement ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Actif ?'),
        ),
    ]
