# Generated by Django 3.0.5 on 2021-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='gar_active',
            field=models.BooleanField(default=0, verbose_name='Actif au GAR'),
        ),
    ]
