# Generated by Django 3.0.5 on 2022-08-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_tiers'),
        ('association', '0017_auto_20220804_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='is_credit',
            field=models.BooleanField(default=0, verbose_name='is_credit ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='is_paypal',
            field=models.BooleanField(default=0, verbose_name='is_paypal ?'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='plan',
            field=models.ForeignKey(blank=True, default=17, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountings', to='association.Plancomptable', verbose_name='Plan comptable'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('town', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Téléphone')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='school.Country', verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('town', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Téléphone')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='school.Country', verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Accountancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_id', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('ranking', models.PositiveIntegerField(default=1, editable=False)),
                ('is_credit', models.BooleanField(default=0, verbose_name='is_credit ?')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Montant')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountancies', to='association.Plancomptable', verbose_name='Plan comptable')),
            ],
        ),
    ]
