# Generated by Django 3.0.5 on 2021-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0017_abonnement_gar_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='is_gar',
            field=models.BooleanField(default=0, editable=False, verbose_name='Usage du GAR'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='gar_active',
            field=models.BooleanField(default=0, editable=False, verbose_name='Actif au GAR'),
        ),
    ]
