# Generated by Django 3.0.5 on 2022-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0017_auto_20220809_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeyear',
            name='solde',
            field=models.IntegerField(default=0, verbose_name="Résultat de l'exercice précédent"),
        ),
    ]
