# Generated by Django 3.0.5 on 2022-08-30 21:59

import association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0018_auto_20220813_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeyear',
            name='balance',
            field=models.FileField(blank=True, default='', upload_to=association.models.compta_directory_path, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='activeyear',
            name='bilan',
            field=models.FileField(blank=True, default='', upload_to=association.models.compta_directory_path, verbose_name='Bilan'),
        ),
        migrations.AddField(
            model_name='activeyear',
            name='book',
            field=models.FileField(blank=True, default='', upload_to=association.models.compta_directory_path, verbose_name='Grand livre'),
        ),
        migrations.AlterField(
            model_name='activeyear',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name="Résultat de l'exercice précédent"),
        ),
    ]
