# Generated by Django 3.0.5 on 2021-04-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0018_auto_20210423_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='accounting',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='association.Accounting'),
        ),
    ]
