# Generated by Django 3.0.5 on 2022-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0018_auto_20220805_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountancy',
            name='plan',
        ),
        migrations.AddField(
            model_name='accountancy',
            name='plan_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Plan comptable'),
        ),
    ]
