# Generated by Django 3.0.5 on 2021-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0019_auto_20210423_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='gar_active',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='is_active',
            field=models.BooleanField(default=0, editable=False, verbose_name='Actif'),
        ),
    ]
