# Generated by Django 3.0.5 on 2022-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0019_auto_20220805_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountancy',
            name='current_year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Année'),
        ),
    ]
