# Generated by Django 3.0.5 on 2021-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0020_auto_20210423_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='code',
        ),
        migrations.AddField(
            model_name='accounting',
            name='chrono',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
