# Generated by Django 3.0.5 on 2022-10-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0020_auto_20220902_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposections', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
            ],
        ),
    ]
