# Generated by Django 3.0.5 on 2022-08-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0020_accountancy_current_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='is_cpca',
        ),
    ]
