# Generated by Django 3.0.5 on 2022-10-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0021_prospection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospection',
            name='user',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospections', to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
    ]
