# Generated by Django 3.0.5 on 2021-05-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0021_auto_20210509_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='mode',
            field=models.CharField(choices=[('Carte de crédit', 'Carte de crédit'), ('Virement bancaire', 'Virement bancaire'), ('Espèces', 'Espèces')], default='Carte de crédit', max_length=255, verbose_name='Mode de paiement'),
        ),
    ]
