# Generated by Django 3.0.5 on 2021-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0022_accounting_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='mode',
            field=models.CharField(blank=True, choices=[('Carte de crédit', 'Carte de crédit'), ('Virement bancaire', 'Virement bancaire'), ('Espèces', 'Espèces')], default='', max_length=255, verbose_name='Mode de paiement'),
        ),
    ]
