# Generated by Django 3.0.5 on 2022-08-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0022_accounting_is_facturation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('town', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Téléphone')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='school.Country', verbose_name='Pays')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='school.School')),
            ],
        ),
    ]
