# Generated by Django 3.0.5 on 2021-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0023_auto_20210510_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='mode',
            field=models.CharField(blank=True, choices=[('par carte de crédit', 'Carte de crédit'), ('par virement bancaire', 'Virement bancaire'), ('en espèces', 'Espèces')], default='', max_length=255, verbose_name='Mode de paiement'),
        ),
    ]
