# Generated by Django 3.0.5 on 2022-08-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0023_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Abonné ?'),
        ),
    ]
