# Generated by Django 3.0.5 on 2022-08-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20220809_1326'),
        ('association', '0024_customer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Perdu'), (1, 'En suspens'), (2, 'Paiement en attente'), (3, 'Abonné')], default=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='school.School'),
        ),
    ]
