# Generated by Django 3.0.5 on 2023-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0024_auto_20230524_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='status',
            field=models.CharField(blank=True, choices=[(0, "Période d'essai"), (1, 'Abonnement')], default='', max_length=255),
        ),
    ]
