# Generated by Django 3.0.5 on 2021-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0024_auto_20210510_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='forme',
            field=models.CharField(blank=True, choices=[('FACTURE', 'FACTURE'), ('AVOIR', 'AVOIR'), ('DEVIS', 'DEVIS')], default='FACTURE', max_length=255, verbose_name='Format'),
        ),
    ]
