# Generated by Django 3.0.5 on 2021-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0025_accounting_forme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_start',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_stop',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='is_gar',
            field=models.BooleanField(default=0, verbose_name='Usage du GAR'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='mode',
            field=models.CharField(blank=True, choices=[('par carte de crédit', 'Carte de crédit'), ('par virement bancaire', 'Virement bancaire'), ('en espèces', 'Espèces'), ('par mandatement administratif', 'Mandatement administratif')], default='', max_length=255, verbose_name='Mode de paiement'),
        ),
    ]
