# Generated by Django 3.0.5 on 2023-05-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0026_auto_20230524_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ouverture compte'), (1, 'En suspens'), (2, 'Paiement en attente'), (3, 'Abonné')], default=2),
        ),
    ]
