# Generated by Django 3.0.5 on 2021-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0026_auto_20210511_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='is_abonnement',
            field=models.BooleanField(default=0, verbose_name='Abonnement'),
        ),
    ]
