# Generated by Django 3.0.5 on 2021-05-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0027_accounting_is_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_start',
            field=models.DateTimeField(blank=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_stop',
            field=models.DateTimeField(blank=True, verbose_name='Date de fin'),
        ),
    ]
