# Generated by Django 3.0.5 on 2023-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0027_auto_20230524_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin d'abonement"),
        ),
        migrations.AddField(
            model_name='customer',
            name='gar_abonnement_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='mode',
            field=models.CharField(blank=True, choices=[('Période de test', "Période d'essai"), ('Abonnement', 'Abonnement'), ('Remboursement', 'Remboursement')], default='', max_length=255, verbose_name='Mode de paiement'),
        ),
    ]
