# Generated by Django 3.0.5 on 2021-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0028_auto_20210512_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='chrono',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
