# Generated by Django 3.0.5 on 2023-05-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0028_auto_20230525_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='actual',
            field=models.PositiveSmallIntegerField(choices=[(0, "Période d'essai"), (1, 'Abonnement')], default=1),
        ),
    ]
