# Generated by Django 3.0.5 on 2023-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0029_customer_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_stop',
            field=models.DateField(blank=True, null=True, verbose_name="Fin d'abonement"),
        ),
    ]
