# Generated by Django 3.0.5 on 2021-05-29 06:25

import association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0029_auto_20210512_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='ticket',
            field=models.FileField(blank=True, default='', upload_to=association.models.accounting_directory_path, verbose_name='Justificatif'),
        ),
    ]
