# Generated by Django 3.0.5 on 2021-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0030_accounting_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='forme',
            field=models.CharField(blank=True, choices=[('FACTURE', 'FACTURE'), ('AVOIR', 'AVOIR'), ('DEVIS', 'DEVIS'), ('REMBOURSEMENT', 'REMBOURSEMENT')], default='FACTURE', max_length=255, verbose_name='Format'),
        ),
    ]
