# Generated by Django 3.0.5 on 2023-06-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0031_customer_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_start_gar',
            field=models.DateField(blank=True, null=True, verbose_name='Abonement GAR'),
        ),
    ]
