# Generated by Django 3.0.5 on 2023-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0032_customer_date_start_gar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_display_button',
            field=models.BooleanField(blank=True, default=0, editable=False),
        ),
    ]
