# Generated by Django 2.1.2 on 2020-04-05 20:36

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('texte', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texte')),
                ('today', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_email', to=settings.AUTH_USER_MODEL)),
                ('receivers', models.ManyToManyField(blank=True, related_name='receiver_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
