# Generated by Django 3.0.5 on 2020-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_merge_20200727_1646'),
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='teachers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='teachers_communication', to='account.Teacher'),
        ),
    ]
