# Generated by Django 3.0.5 on 2020-10-26 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_communication_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='today',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
