# Generated by Django 3.0.5 on 2020-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='today',
            field=models.DateField(auto_now_add=True),
        ),
    ]
