# Generated by Django 3.0.5 on 2021-03-02 17:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendmail', '0003_auto_20201026_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('0', 'Sacado'), ('1', 'Pédagogie et Didactique'), ('2', 'Geogebra'), ('3', 'Python'), ('4', 'Jeu et concours')], max_length=10, verbose_name='Catégorie')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('texte', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texte')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=1, verbose_name='Afficher la communication ?')),
                ('solve', models.BooleanField(default=0, verbose_name='Résolu ?')),
                ('answers', models.ManyToManyField(blank=True, related_name='_message_answers_+', to='sendmail.Message')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_message', to='socle.Subject')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
