# Generated by Django 3.0.5 on 2021-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(blank=True, choices=[('Sacado', 'Sacado'), ('Pédagogie et Didactique', 'Pédagogie et Didactique'), ('Geogebra', 'Geogebra'), ('Python', 'Python'), ('Jeu et concours', 'Jeu et concours')], max_length=100, verbose_name='Catégorie'),
        ),
    ]
