# Generated by Django 3.0.5 on 2021-03-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socle', '0007_auto_20201215_0741'),
        ('sendmail', '0006_auto_20210302_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.RemoveField(
            model_name='message',
            name='solve',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Sacado', 'Sacado'), ('Pédagogie et Didactique', 'Pédagogie et Didactique'), ('Geogebra', 'Geogebra'), ('Python', 'Python'), ('Jeu et concours', 'Jeu et concours')], max_length=100, verbose_name='Catégorie')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=1, verbose_name='Afficher la communication ?')),
                ('solve', models.BooleanField(default=0, verbose_name='Résolu ?')),
                ('subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_discussion', to='socle.Subject')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_discussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_message', to='sendmail.Discussion'),
        ),
    ]
