# Generated by Django 3.0.5 on 2021-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0007_auto_20210302_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='nb_display',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
