# Generated by Django 3.0.5 on 2020-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('adhesion_month', models.CharField(default='', max_length=255, verbose_name='par mois')),
                ('adhesion_half', models.CharField(default='', max_length=255, verbose_name='par trimestre')),
                ('total_half', models.CharField(default='', editable=False, max_length=255)),
                ('adhesion_year', models.CharField(default='', max_length=255, verbose_name='par an')),
                ('total_year', models.CharField(default='', editable=False, max_length=255)),
                ('family_adhesion_month', models.CharField(default='', max_length=255, verbose_name='par mois')),
                ('family_adhesion_half', models.CharField(default='', max_length=255, verbose_name='par trimestre')),
                ('family_total_half', models.CharField(default='', editable=False, max_length=255)),
                ('family_adhesion_year', models.CharField(default='', max_length=255, verbose_name='par an')),
                ('family_total_year', models.CharField(default='', editable=False, max_length=255)),
            ],
        ),
    ]
