# Generated by Django 3.0.5 on 2020-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formule',
            name='family_total_half',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='formule',
            name='family_total_year',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='formule',
            name='total_half',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='formule',
            name='total_year',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
