# Generated by Django 3.0.5 on 2020-12-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20201213_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formule',
            name='family_total_year',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='total_year',
        ),
    ]
