# Generated by Django 3.0.5 on 2020-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20201213_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formule',
            name='family_adhesion_half',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='family_adhesion_month',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='family_adhesion_year',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='family_total_half',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='total_half',
        ),
        migrations.AddField(
            model_name='formule',
            name='adhesion',
            field=models.CharField(default='', max_length=255, verbose_name='adhesion'),
        ),
        migrations.AddField(
            model_name='formule',
            name='is_family',
            field=models.BooleanField(default=0, verbose_name='Forfait famille ?'),
        ),
    ]
