# Generated by Django 3.0.5 on 2020-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20201213_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formule',
            name='adhesion_half',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='adhesion_month',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='adhesion_year',
        ),
        migrations.AddField(
            model_name='formule',
            name='price',
            field=models.CharField(default='', max_length=255, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='adhesion',
            field=models.CharField(default='', max_length=255, verbose_name='Adhesion'),
        ),
    ]
