# Generated by Django 3.0.5 on 2020-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20201213_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='nb_month',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de mois'),
        ),
    ]
