# Generated by Django 3.0.5 on 2023-04-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20230409_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edt',
            name='is_saturday',
        ),
        migrations.RemoveField(
            model_name='edt',
            name='is_wednesday',
        ),
        migrations.AddField(
            model_name='edt',
            name='days_on',
            field=models.CharField(default='Lundi-Mardi-Mercredi-Jeudi-Vendredi-Samedi', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='edt',
            name='first_day',
            field=models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('0', 'Dimanche')], default='0', max_length=250),
        ),
    ]
