# Generated by Django 3.0.5 on 2023-04-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20230409_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='edt',
            name='start_class',
            field=models.CharField(blank=True, default='8:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='edt',
            name='first_day',
            field=models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche')], default='0', max_length=250),
        ),
    ]
