# Generated by Django 3.0.5 on 2023-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_template_edt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_edt',
            name='day',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.RemoveField(
            model_name='template_edt',
            name='slot',
        ),
        migrations.AddField(
            model_name='template_edt',
            name='slot',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
