# Generated by Django 3.0.5 on 2023-04-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20230412_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template_edt',
            old_name='user',
            new_name='edt',
        ),
    ]
