# Generated by Django 3.0.5 on 2023-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20230412_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_edt',
            name='is_half',
            field=models.BooleanField(default=0),
        ),
    ]
