# Generated by Django 3.0.5 on 2023-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_template_edt_is_half'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotedt',
            name='start',
            field=models.DateField(verbose_name='start'),
        ),
    ]
