# Generated by Django 3.0.5 on 2023-04-17 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_auto_20230415_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edt',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edt', to=settings.AUTH_USER_MODEL),
        ),
    ]
