# Generated by Django 3.0.5 on 2023-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20230417_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='edt',
            name='is_share',
            field=models.BooleanField(default=1),
        ),
    ]
