# Generated by Django 3.0.5 on 2023-05-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_connexion'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='teacher',
            field=models.ForeignKey(default='2480', on_delete=django.db.models.deletion.CASCADE, related_name='doctypes', to='account.Teacher', verbose_name='teacher'),
        ),
    ]
