# Generated by Django 3.0.5 on 2023-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='color',
            field=models.CharField(default='#5d4391', max_length=255, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='book',
            name='color_hover',
            field=models.CharField(default='#9274C7', max_length=255, verbose_name='Couleur hover'),
        ),
    ]
