# Generated by Django 3.0.5 on 2023-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_connexion'),
        ('book', '0002_doctype_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctype',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doctype',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien externe'),
        ),
    ]
