# Generated by Django 3.0.5 on 2023-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20230528_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='color',
            field=models.CharField(blank=True, default='#5d4391', max_length=255, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='color_hover',
            field=models.CharField(blank=True, default='#9274C7', max_length=255, verbose_name='Couleur hover'),
        ),
    ]
