# Generated by Django 3.0.5 on 2023-05-21 15:51

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_connexion'),
        ('book', '0003_auto_20230521_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doctype',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=book.models.document_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(default='2480', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='account.Teacher', verbose_name='teacher'),
        ),
    ]
