# Generated by Django 3.0.5 on 2023-05-28 22:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('book', '0003_auto_20230528_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('css', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la classe')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Typebloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('css', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la classe')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='book.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField(blank=True, verbose_name='Enoncé en LaTeX')),
                ('content_html', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Enoncé pour html')),
                ('correction', models.TextField(blank=True, default='', null=True, verbose_name='Corrigé')),
                ('correction_html', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Correction pour html')),
                ('duration', models.PositiveIntegerField(blank=True, default=15, verbose_name='Durée estimée - en minutes')),
                ('is_calculator', models.BooleanField(default=0, verbose_name='Calculatrice ?')),
                ('is_python', models.BooleanField(default=0, verbose_name='Python ?')),
                ('is_scratch', models.BooleanField(default=0, verbose_name='Scratch ?')),
                ('is_tableur', models.BooleanField(default=0, verbose_name='Tableur ?')),
                ('is_corrected', models.BooleanField(default=0, verbose_name='Correction ?')),
                ('is_annals', models.BooleanField(default=0, verbose_name='Annale ?')),
                ('knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='socle.Knowledge', verbose_name='Savoir faire associé')),
                ('knowledges', models.ManyToManyField(blank=True, related_name='other_knowledge_blocs', to='socle.Knowledge', verbose_name='Savoir faire associés complémentaires')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='book.Paragraph')),
                ('skills', models.ManyToManyField(blank=True, related_name='blocs', to='socle.Skill', verbose_name='Compétences ciblées')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='socle.Theme', verbose_name='Thème')),
                ('typebloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='book.Typebloc', verbose_name='Type de bloc')),
            ],
        ),
    ]
