# Generated by Django 3.0.5 on 2023-05-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0022_auto_20230418_0916'),
        ('qcm', '0096_auto_20230504_1753'),
        ('book', '0004_bloc_page_paragraph_typebloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='exercise',
            field=models.ManyToManyField(blank=True, related_name='blocs', to='qcm.Exercise', verbose_name='Exercices connexes'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='exotex',
            field=models.ManyToManyField(blank=True, related_name='blocs', to='bibliotex.Exotex', verbose_name='ExoTex connexes'),
        ),
    ]
