# Generated by Django 3.0.5 on 2023-05-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('account', '0030_connexion'),
        ('book', '0004_auto_20230521_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_documents', to='account.Teacher', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='document',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='socle.Subject', verbose_name='Enseignement'),
        ),
    ]
