# Generated by Django 3.0.5 on 2023-05-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20230528_2313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('number', 'book')},
        ),
    ]
