# Generated by Django 3.0.5 on 2023-05-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20230521_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='flashcard',
        ),
        migrations.RemoveField(
            model_name='document',
            name='question',
        ),
    ]
