# Generated by Django 3.0.5 on 2023-05-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20230529_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='book.Chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('number', 'chapter')},
        ),
        migrations.RemoveField(
            model_name='page',
            name='book',
        ),
    ]
