# Generated by Django 3.0.5 on 2023-05-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20230529_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloc',
            old_name='exercise',
            new_name='exercises',
        ),
        migrations.RenameField(
            model_name='bloc',
            old_name='exotex',
            new_name='exotexs',
        ),
    ]
