# Generated by Django 3.0.5 on 2023-05-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_connexion'),
        ('book', '0007_auto_20230527_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='document',
            name='teachers',
        ),
        migrations.AddField(
            model_name='chapter',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_chapters', to='account.Teacher', verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='document',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.Teacher', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_chapters', to='account.Teacher', verbose_name='Enseignant'),
        ),
    ]
