# Generated by Django 3.0.5 on 2023-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20230527_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='bibliotex',
        ),
        migrations.RemoveField(
            model_name='document',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='document',
            name='exotex',
        ),
        migrations.RemoveField(
            model_name='document',
            name='flashpack',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quizz',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
