# Generated by Django 3.0.5 on 2023-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20230530_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
