# Generated by Django 3.0.5 on 2023-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20230530_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
