# Generated by Django 3.0.5 on 2023-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_paragraph_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
