# Generated by Django 3.0.5 on 2023-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_bloc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(blank=True, default='#9274C7', max_length=15, null=True, verbose_name='Couleur'),
        ),
    ]
