# Generated by Django 3.0.5 on 2023-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_section_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_publish',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
