# Generated by Django 3.0.5 on 2023-05-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0096_auto_20230504_1753'),
        ('book', '0014_section_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='parcours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='qcm.Parcours'),
        ),
    ]
