# Generated by Django 3.0.5 on 2023-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_chapter_parcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentex',
            name='is_done',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Effectué ?'),
        ),
    ]
