# Generated by Django 3.0.5 on 2023-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_documentex_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentex',
            name='is_done',
        ),
        migrations.AddField(
            model_name='document',
            name='is_done',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Effectué ?'),
        ),
    ]
