# Generated by Django 3.0.5 on 2023-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20230531_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='Cours', max_length=255, verbose_name='Titre de la page'),
        ),
    ]
