# Generated by Django 3.0.5 on 2023-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(12, 'Page entière'), (6, '1/2 page'), (4, '1/3 page'), (3, '1/4 page'), (2, '1/6 page')], default=12, verbose_name='Colonne'),
        ),
    ]
