# Generated by Django 3.0.5 on 2023-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_bloc_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliquette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(max_length=255, verbose_name='Forme')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('iframe', models.TextField(verbose_name='Iframe')),
            ],
        ),
    ]
