# Generated by Django 3.0.5 on 2023-06-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('book', '0020_appliquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliquette',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appliquettes', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='appliquette',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='appliquette',
            name='forme',
            field=models.CharField(default='', max_length=255, verbose_name='Forme'),
        ),
        migrations.AlterField(
            model_name='appliquette',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
    ]
