# Generated by Django 3.0.5 on 2023-08-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20230801_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
