# Generated by Django 3.0.5 on 2023-08-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20230801_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='appliquette',
            field=models.ManyToManyField(blank=True, related_name='blocs', to='book.Appliquette', verbose_name='Appliquettes'),
        ),
    ]
