# Generated by Django 3.0.5 on 2023-08-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_bloc_appliquette'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloc',
            old_name='appliquette',
            new_name='appliquettes',
        ),
    ]
