# Generated by Django 3.0.5 on 2023-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20230802_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='theme',
            field=models.CharField(blank=True, choices=[('NC', 'Nombres et calculs'), ('G', 'Géométrie'), ('F', 'Fonctions'), ('SP', 'Stats et probabilités'), ('GM', 'Grandeurs et Mesures'), ('A', 'Algèbre'), ('OGD', 'Organisation et Gestion de données')], max_length=255, null=True, verbose_name='Thème'),
        ),
    ]
