# Generated by Django 3.0.5 on 2023-08-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0102_docperso_subject'),
        ('book', '0028_auto_20230817_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parcours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='qcm.Parcours'),
        ),
    ]
