# Generated by Django 3.0.5 on 2023-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_bloc_is_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_progression',
            field=models.BooleanField(default=1, verbose_name='Dans ma progression ?'),
        ),
    ]
