# Generated by Django 3.0.5 on 2023-09-02 07:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_chapter_is_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='content_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Enoncé pour html'),
        ),
    ]
