# Generated by Django 3.0.5 on 2023-09-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_auto_20230902_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_publish',
            field=models.BooleanField(default=1, verbose_name='Publiée ?'),
        ),
    ]
