# Generated by Django 3.0.5 on 2023-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_page_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloc',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(12, 'Page entière'), (10, '5/6 page'), (9, '3/4 page'), (8, '2/3 page'), (7, '7/12 page'), (6, '1/2 page'), (5, '5/12 page'), (4, '1/3 page'), (3, '1/4 page'), (2, '1/6 page')], default=12, verbose_name='Colonne'),
        ),
    ]
