# Generated by Django 3.0.5 on 2023-11-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0032_flashpack_ranking'),
        ('book', '0034_auto_20231031_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='flashpack',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='flashcard.Flashpack'),
        ),
    ]
