# Generated by Django 3.0.5 on 2023-11-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_chapter_flashpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='insidebloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Bloc', verbose_name='Dans le bloc'),
        ),
    ]
