# Generated by Django 3.0.5 on 2023-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_bloc_insidebloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebloc',
            name='latexbloc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latex Bloc'),
        ),
        migrations.AddField(
            model_name='typebloc',
            name='latextype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latex type'),
        ),
    ]
