# Generated by Django 3.0.4 on 2024-01-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20230928_0655'),
        ('book', '0037_auto_20231112_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_display', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('book', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mybooks', to='book.Book')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybooks', to='group.Group', verbose_name='Participants')),
            ],
        ),
        migrations.CreateModel(
            name='Mybloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_display_cor', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('is_display_comp', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('bloc', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='myblocs', to='book.Bloc')),
                ('mybook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myblocs', to='book.Mybook', verbose_name='Participants')),
            ],
        ),
    ]
