# Generated by Django 3.0.4 on 2024-01-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20230928_0655'),
        ('book', '0038_mybloc_mybook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybloc',
            name='mybook',
        ),
        migrations.AddField(
            model_name='mybloc',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myblocs', to='group.Group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybooks', to='group.Group', verbose_name='Groupe'),
        ),
    ]
