# Generated by Django 3.0.4 on 2024-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_auto_20240123_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybloc',
            name='is_display_comp',
            field=models.BooleanField(default=1, verbose_name='Publié ?'),
        ),
    ]
