# Generated by Django 3.0.5 on 2021-01-20 07:34

import account.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        ('account', '0022_user_is_testeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse écrite')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Titre')),
                ('remark', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte*')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('imagefile', models.ImageField(default='', upload_to=tool.models.tool_directory_path, verbose_name='Image')),
                ('is_publish', models.BooleanField(default=1, verbose_name='Publié ?')),
                ('teacher', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='account.Teacher')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teacher_tools', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du quizz')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('vignette', models.ImageField(blank=True, default='', null=True, upload_to=tool.models.quizz_directory_path, verbose_name="Vignette d'accueil")),
                ('is_music', models.BooleanField(default=0, verbose_name='En musique ?')),
                ('is_share', models.BooleanField(default=0, verbose_name='Mutualisé ?')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('is_questions', models.BooleanField(default=0, editable=False)),
                ('is_mark', models.BooleanField(default=0, verbose_name='Type de réponse')),
                ('levels', models.ManyToManyField(blank=True, related_name='quizz', to='socle.Level')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='socle.Subject')),
                ('teacher', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_quizz', to='account.Teacher')),
                ('themes', models.ManyToManyField(blank=True, related_name='quizz', to='socle.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Réponse écrite')),
                ('calculator', models.BooleanField(default=0, verbose_name='Calculatrice ?')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('kind', models.PositiveIntegerField(default=3, editable=False)),
                ('imagefile', models.ImageField(blank=True, default='', upload_to=tool.models.question_directory_path, verbose_name='Image')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('is_radio', models.BooleanField(default=0, verbose_name='Type de réponse ?')),
                ('is_correction', models.BooleanField(default=0, verbose_name='Correction ?')),
                ('duration', models.PositiveIntegerField(blank=True, default=20, verbose_name='Durée')),
                ('point', models.PositiveIntegerField(blank=True, default=1000, verbose_name='Point')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('choices', models.ManyToManyField(blank=True, related_name='questions', to='tool.Choice', verbose_name='Réponse')),
                ('quizzes', models.ManyToManyField(blank=True, editable=False, related_name='questions', to='tool.Quizz')),
            ],
        ),
    ]
