# Generated by Django 3.0.5 on 2021-02-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrandom',
            name='tool',
            field=models.BooleanField(default=0, verbose_name="Barre d'outils ?"),
        ),
    ]
