# Generated by Django 3.0.5 on 2021-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='themeeee',
            field=models.BooleanField(default=0, verbose_name='Thème ?'),
        ),
    ]
