# Generated by Django 3.0.5 on 2021-06-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='themeeee',
        ),
    ]
