# Generated by Django 3.0.5 on 2021-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_asso',
            field=models.BooleanField(default=1, verbose_name="Nécessite l'adhésion SACADO ?"),
        ),
    ]
