# Generated by Django 3.0.5 on 2021-01-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_tool_is_asso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='teacher',
        ),
    ]
