# Generated by Django 3.0.5 on 2021-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_is_testeur'),
        ('tool', '0003_remove_tool_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='teachers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='tools', to='account.Teacher'),
        ),
    ]
