# Generated by Django 3.0.5 on 2021-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20210209_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrandom',
            name='tool',
            field=models.BooleanField(default=0, verbose_name="Barre d'outils ?"),
        ),
    ]
