# Generated by Django 3.0.5 on 2021-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20210209_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='nb_slide',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
