# Generated by Django 3.0.5 on 2021-01-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20210120_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='url'),
        ),
    ]
