# Generated by Django 3.0.5 on 2021-02-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_quizz_nb_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='nb_slide',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
