# Generated by Django 3.0.5 on 2021-02-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20210209_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic_qqr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_text', models.TextField(editable=False)),
                ('ranking', models.PositiveIntegerField(default=1, editable=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('quizz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='tool.Quizz')),
            ],
        ),
    ]
