# Generated by Django 3.0.5 on 2021-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20210122_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='is_numeric',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
