# Generated by Django 3.0.5 on 2021-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_historic_qqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic_qqr',
            name='code_uuid',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
