# Generated by Django 3.0.5 on 2021-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20201229_1908'),
        ('tool', '0007_quizz_is_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='group.Group'),
        ),
    ]
