# Generated by Django 3.0.5 on 2021-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_quizz_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='is_mark',
            field=models.BooleanField(default=0, verbose_name='Récupérer les notes ?'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='is_numeric',
            field=models.BooleanField(default=0, verbose_name='Type de réponse'),
        ),
    ]
