# Generated by Django 3.0.5 on 2021-02-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20201229_1908'),
        ('tool', '0008_historic_qqr_code_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historic_qqr',
            name='group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='group.Group'),
        ),
    ]
