# Generated by Django 3.0.5 on 2021-01-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_is_testeur'),
        ('tool', '0009_auto_20210123_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='account.Student'),
        ),
    ]
