# Generated by Django 3.0.5 on 2021-02-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('group', '0014_auto_20201229_1908'),
        ('tool', '0009_historic_qqr_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_qr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_text', models.TextField(editable=False)),
                ('ranking', models.PositiveIntegerField(default=1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Generate_quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='group.Group')),
                ('quizz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='generate_quizz', to='tool.Quizz')),
            ],
        ),
        migrations.CreateModel(
            name='Historic_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', editable=False, max_length=255)),
                ('duration', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=0, editable=False)),
                ('gq', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='tool.Generate_quizz')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz_student_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwser', models.CharField(editable=False, max_length=255)),
                ('is_correct', models.BooleanField(default=0, editable=False)),
                ('qrandom', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizz_student_answers', to='tool.Generate_qr')),
                ('question', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizz_student_answers', to='tool.Question')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quizz_student_answers', to='account.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Historic_qqr',
        ),
        migrations.AddField(
            model_name='generate_qr',
            name='quizz',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='generate_qr', to='tool.Generate_quizz'),
        ),
    ]
