# Generated by Django 3.0.5 on 2021-02-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20201229_1908'),
        ('tool', '0010_auto_20210210_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_quizz',
            name='group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generate_quizz', to='group.Group'),
        ),
    ]
