# Generated by Django 3.0.5 on 2021-01-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_is_testeur'),
        ('tool', '0010_quizz_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='students',
        ),
        migrations.AddField(
            model_name='quizz',
            name='is_lock',
            field=models.BooleanField(default=0, verbose_name='Verrouiller ?'),
        ),
        migrations.CreateModel(
            name='Questionplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Réponse')),
                ('score', models.PositiveIntegerField(default=0, editable=False)),
                ('timer', models.CharField(editable=False, max_length=255)),
                ('question', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_player', to='tool.Question')),
                ('student', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_player', to='account.Student')),
            ],
            options={
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='question', through='tool.Questionplayer', to='account.Student'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoretotal', models.PositiveIntegerField(default=0, editable=False)),
                ('quizz', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='tool.Quizz')),
                ('student', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to='account.Student')),
            ],
            options={
                'unique_together': {('student', 'quizz')},
            },
        ),
    ]
