# Generated by Django 3.0.5 on 2021-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_auto_20210124_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='interslide',
            field=models.PositiveIntegerField(blank=True, default=10, verbose_name='Temps entre les questions'),
        ),
    ]
