# Generated by Django 3.0.5 on 2021-02-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_auto_20210210_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate_qr',
            old_name='quizz',
            new_name='gquizz',
        ),
    ]
