# Generated by Django 3.0.5 on 2021-02-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0012_auto_20210210_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz_student_answer',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=20, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='quizz_student_answer',
            unique_together={('qrandom', 'student')},
        ),
        migrations.DeleteModel(
            name='Historic_answer',
        ),
    ]
