# Generated by Django 3.0.5 on 2021-01-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        ('tool', '0012_quizz_interslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='socle.Knowledge'),
        ),
    ]
