# Generated by Django 3.0.5 on 2021-02-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_auto_20210210_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse attendu'),
        ),
    ]
