# Generated by Django 3.0.5 on 2021-02-02 21:35

import account.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('group', '0014_auto_20201229_1908'),
        ('socle', '0007_auto_20201215_0741'),
        ('tool', '0013_question_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Titre')),
                ('texte', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Texte ')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('interslide', models.PositiveIntegerField(blank=True, default=10, verbose_name='Temps entre les questions')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
            ],
        ),
        migrations.CreateModel(
            name='Diaporama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du quizz')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('vignette', models.ImageField(blank=True, default='', null=True, upload_to=tool.models.quizz_directory_path, verbose_name="Vignette d'accueil")),
                ('is_share', models.BooleanField(default=0, verbose_name='Mutualisé ?')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('groups', models.ManyToManyField(blank=True, editable=False, related_name='presentation', to='group.Group')),
                ('levels', models.ManyToManyField(blank=True, related_name='presentation', to='socle.Level')),
                ('slides', models.ManyToManyField(blank=True, editable=False, related_name='diapositive', to='tool.Slide')),
                ('students', models.ManyToManyField(blank=True, editable=False, related_name='user_presentation', to='account.Student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='socle.Subject')),
                ('teacher', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_presentation', to='account.Teacher')),
                ('themes', models.ManyToManyField(blank=True, related_name='presentation', to='socle.Theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
