# Generated by Django 3.0.5 on 2021-02-12 22:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_quizz',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
    ]
