# Generated by Django 3.0.5 on 2021-02-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0014_diaporama_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='interslide',
            new_name='duration',
        ),
    ]
