# Generated by Django 3.0.5 on 2021-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_generate_quizz_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_quizz',
            name='mode',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
