# Generated by Django 3.0.5 on 2021-02-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0015_auto_20210203_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='texte',
            new_name='content',
        ),
    ]
