# Generated by Django 3.0.5 on 2021-02-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_generate_quizz_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generate_quizz',
            old_name='mode',
            new_name='is_game',
        ),
    ]
