# Generated by Django 3.0.5 on 2021-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_auto_20210203_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='is_random',
            field=models.BooleanField(default=0, verbose_name='Questions générées aléatoirement'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="Durée d'affichage"),
        ),
    ]
