# Generated by Django 3.0.5 on 2021-02-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0017_auto_20210213_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_quizz',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='generate_quizz', to='account.Student'),
        ),
    ]
