# Generated by Django 3.0.5 on 2021-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_auto_20210205_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='is_random',
            field=models.BooleanField(default=0, verbose_name='Aléatoire ?'),
        ),
    ]
