# Generated by Django 3.0.5 on 2022-10-25 13:57

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_auto_20220402_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Type')),
                ('imagefile', models.ImageField(blank=True, default='', upload_to=tool.models.qtype_directory_path, verbose_name='Image')),
                ('html', models.TextField(blank=True, default='', verbose_name='Html éventuel')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=100, verbose_name='Point'),
        ),
    ]
