# Generated by Django 3.0.5 on 2021-02-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0018_generate_quizz_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate_quizz',
            name='students',
        ),
        migrations.AddField(
            model_name='generate_qr',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='generate_qr', through='tool.Questionplayer', to='account.Student'),
        ),
        migrations.AddField(
            model_name='questionplayer',
            name='qrandom',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_player', to='tool.Generate_qr'),
        ),
        migrations.AlterField(
            model_name='question',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='questions', through='tool.Questionplayer', to='account.Student'),
        ),
        migrations.AlterField(
            model_name='questionplayer',
            name='question',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_player', to='tool.Question'),
        ),
        migrations.AlterField(
            model_name='questionplayer',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_player', to='account.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='questionplayer',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
