# Generated by Django 3.0.5 on 2021-02-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_auto_20210205_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quizzes',
        ),
        migrations.AddField(
            model_name='quizz',
            name='questions',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='tool.Question'),
        ),
    ]
