# Generated by Django 3.0.5 on 2022-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0018_auto_20221025_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='is_online',
            field=models.BooleanField(default=0, verbose_name='En ligne ?'),
        ),
        migrations.AddField(
            model_name='qtype',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='url'),
        ),
    ]
