# Generated by Django 3.0.5 on 2021-02-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_auto_20210206_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='kind',
            new_name='qtype',
        ),
        migrations.AlterField(
            model_name='question',
            name='is_publish',
            field=models.BooleanField(default=1, verbose_name='Publié ?'),
        ),
    ]
