# Generated by Django 3.0.5 on 2021-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0019_auto_20210214_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_quizz',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='gquizz', to='account.Student'),
        ),
    ]
