# Generated by Django 3.0.5 on 2022-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0019_auto_20221025_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='template',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='template'),
        ),
    ]
