# Generated by Django 3.0.5 on 2021-02-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_generate_quizz_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_qr',
            name='qrandom',
            field=models.ManyToManyField(blank=True, editable=False, related_name='generate_qr', to='tool.Qrandom'),
        ),
    ]
