# Generated by Django 3.0.5 on 2022-10-26 08:57

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_qtype_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse écrite')),
                ('retroaction', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Rétroaction')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchoices', to='tool.Choice')),
            ],
        ),
    ]
