# Generated by Django 3.0.5 on 2021-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0020_auto_20210206_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(default=1, verbose_name='Réponse correcte ?'),
        ),
    ]
