# Generated by Django 3.0.5 on 2021-02-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0021_generate_qr_qrandom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Réponse')),
                ('score', models.PositiveIntegerField(default=0, editable=False)),
                ('timer', models.CharField(editable=False, max_length=255)),
                ('is_correct', models.BooleanField(default=0, editable=False)),
                ('qrandom', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_player', to='tool.Generate_qr')),
                ('question', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_player', to='tool.Question')),
                ('student', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_player', to='account.Student')),
            ],
        ),
        migrations.AddField(
            model_name='quizz_student_answer',
            name='score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quizz_student_answer',
            name='duration',
            field=models.DurationField(blank=True, default='', editable=False),
        ),
        migrations.DeleteModel(
            name='Questionplayer',
        ),
        migrations.AlterField(
            model_name='generate_qr',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='generate_qr', through='tool.Answerplayer', to='account.Student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='questions', through='tool.Answerplayer', to='account.Student'),
        ),
    ]
