# Generated by Django 3.0.5 on 2022-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0021_subchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='filltheblanks',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Texte à trous'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Enoncé'),
        ),
    ]
