# Generated by Django 3.0.5 on 2022-10-26 09:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_auto_20221026_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='filltheblanks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=255, verbose_name='Texte à trous'),
        ),
    ]
