# Generated by Django 3.0.5 on 2021-02-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0022_auto_20210215_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quizz_student_answer',
        ),
    ]
