# Generated by Django 3.0.5 on 2021-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0023_delete_quizz_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_qr',
            name='is_game',
            field=models.BooleanField(default=0, editable=False),
        ),
    ]
