# Generated by Django 3.0.5 on 2021-02-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        ('tool', '0023_auto_20210206_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varforq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=20, verbose_name='variable')),
                ('maximum', models.IntegerField(default=10)),
                ('minimum', models.IntegerField(default=0)),
                ('is_integer', models.BooleanField(default=1, verbose_name='Valeur entière ?')),
                ('is_number', models.BooleanField(default=1, verbose_name='Valeur numérique ?')),
            ],
        ),
        migrations.CreateModel(
            name='Qrandomized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Question')),
                ('knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionrandom', to='socle.Knowledge')),
            ],
        ),
    ]
