# Generated by Django 3.0.5 on 2021-02-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0024_generate_qr_is_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate_qr',
            name='is_game',
        ),
        migrations.RemoveField(
            model_name='generate_qr',
            name='qrandom',
        ),
    ]
