# Generated by Django 3.0.5 on 2021-02-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
        ('tool', '0024_qrandomized_varforq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Texte')),
                ('knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrandom', to='socle.Knowledge')),
            ],
        ),
        migrations.AddField(
            model_name='varforq',
            name='imagefiles',
            field=models.TextField(blank=True, max_length=255, verbose_name="Liste d'images"),
        ),
        migrations.AddField(
            model_name='varforq',
            name='is_images',
            field=models.BooleanField(default=0, verbose_name='Type de variable ?'),
        ),
        migrations.AddField(
            model_name='varforq',
            name='words',
            field=models.TextField(blank=True, max_length=255, verbose_name='Liste de valeurs'),
        ),
        migrations.DeleteModel(
            name='Qrandomized',
        ),
        migrations.AddField(
            model_name='varforq',
            name='qrandom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='tool.Qrandom'),
        ),
    ]
