# Generated by Django 3.0.5 on 2022-11-02 11:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0024_auto_20221026_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='filltheblanks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Texte à trous'),
        ),
    ]
