# Generated by Django 3.0.5 on 2022-11-02 11:28

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_auto_20221102_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answerbis',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse par paire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='imageanswerbis',
            field=models.ImageField(blank=True, default='', null=True, upload_to=tool.models.choice_directory_path, verbose_name='Image par paire'),
        ),
    ]
