# Generated by Django 3.0.5 on 2021-02-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0025_auto_20210207_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varforq',
            new_name='Variable',
        ),
    ]
