# Generated by Django 3.0.5 on 2022-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0026_auto_20221102_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='ranking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
