# Generated by Django 3.0.5 on 2021-02-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0026_generate_qr_qrandom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate_qr',
            name='qrandom',
        ),
        migrations.AddField(
            model_name='generate_qr',
            name='qrandom',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generate_qr', to='tool.Qrandom'),
        ),
    ]
