# Generated by Django 3.0.5 on 2021-02-07 11:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0026_auto_20210207_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrandom',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte'),
        ),
    ]
