# Generated by Django 3.0.5 on 2021-02-07 11:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0027_auto_20210207_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrandom',
            name='texte',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='qrandom',
            name='title',
            field=models.TextField(blank=True, max_length=20, verbose_name='title'),
        ),
    ]
