# Generated by Django 3.0.5 on 2022-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0027_qtype_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_ia',
            field=models.BooleanField(default=1, verbose_name='IA ?'),
        ),
    ]
