# Generated by Django 3.0.5 on 2021-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_auto_20210207_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrandom',
            name='is_publish',
            field=models.BooleanField(default=1, verbose_name='Publié ?'),
        ),
    ]
