# Generated by Django 3.0.5 on 2022-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_question_is_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_ia',
            field=models.BooleanField(default=0, verbose_name='IA ?'),
        ),
    ]
