# Generated by Django 3.0.5 on 2021-02-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0028_display_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Display_question',
        ),
    ]
