# Generated by Django 3.0.5 on 2021-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_qrandom_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrandom',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='variable'),
        ),
    ]
