# Generated by Django 3.0.5 on 2022-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_auto_20221109_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='Précision'),
        ),
        migrations.AddField(
            model_name='question',
            name='tick',
            field=models.FloatField(blank=True, null=True, verbose_name='Graduation'),
        ),
        migrations.AddField(
            model_name='question',
            name='xmax',
            field=models.FloatField(blank=True, null=True, verbose_name='x max '),
        ),
        migrations.AddField(
            model_name='question',
            name='xmin',
            field=models.FloatField(blank=True, null=True, verbose_name='x min '),
        ),
    ]
