# Generated by Django 3.0.5 on 2021-02-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0029_delete_display_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(default=0)),
                ('timestamp', models.CharField(max_length=255)),
                ('gquizz_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='display_questions', to='tool.Generate_quizz')),
            ],
        ),
    ]
