# Generated by Django 3.0.5 on 2022-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0030_auto_20221113_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pseudoalea_nb',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
