# Generated by Django 3.0.5 on 2021-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0030_auto_20210207_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='words',
            field=models.CharField(blank=True, max_length=255, verbose_name='Liste de valeurs'),
        ),
    ]
