# Generated by Django 3.0.5 on 2021-02-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0030_display_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_question',
            old_name='gquizz_id',
            new_name='gquizz',
        ),
    ]
