# Generated by Django 3.0.5 on 2021-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0031_auto_20210207_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='is_images',
            field=models.BooleanField(default=0, verbose_name='Images ?'),
        ),
    ]
