# Generated by Django 3.0.5 on 2021-02-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0031_auto_20210216_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerplayer',
            name='gquizz',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answerplayer', to='tool.Generate_quizz'),
            preserve_default=False,
        ),
    ]
