# Generated by Django 3.0.5 on 2022-11-25 13:04

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0031_question_pseudoalea_nb'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableqImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variableq_img', to='tool.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='Variableq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='variable')),
                ('is_integer', models.BooleanField(default=1, verbose_name='Valeur entière ?')),
                ('maximum', models.IntegerField(default=10)),
                ('minimum', models.IntegerField(default=0)),
                ('words', models.TextField(blank=True, verbose_name='Liste de valeurs')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variableqs', to='tool.Qrandom')),
            ],
        ),
    ]
