# Generated by Django 3.0.5 on 2021-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0032_auto_20210207_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_words',
            field=models.BooleanField(default=0, verbose_name='Liste de mots ?'),
        ),
    ]
