# Generated by Django 3.0.5 on 2021-02-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0032_answerplayer_gquizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerplayer',
            name='gquizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerplayer', to='tool.Generate_quizz'),
        ),
    ]
