# Generated by Django 3.0.5 on 2022-11-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0033_auto_20221125_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableq',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variableqs', to='tool.Question'),
        ),
    ]
