# Generated by Django 3.0.5 on 2021-02-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0033_auto_20210216_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='display_question',
            name='student',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_questions', to='account.Student'),
        ),
    ]
