# Generated by Django 3.0.5 on 2021-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0033_variable_is_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='words',
            field=models.TextField(blank=True, max_length=255, verbose_name='Liste de valeurs'),
        ),
    ]
