# Generated by Django 3.0.5 on 2021-02-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0034_display_question_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_question',
            old_name='student',
            new_name='students',
        ),
    ]
