# Generated by Django 3.0.5 on 2022-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0034_auto_20221125_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableq',
            name='is_notnull',
            field=models.BooleanField(default=1, verbose_name='Exclure 0 ?'),
        ),
        migrations.AlterField(
            model_name='variableq',
            name='minimum',
            field=models.IntegerField(default=-10),
        ),
    ]
