# Generated by Django 3.0.5 on 2021-02-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0034_auto_20210207_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='is_images',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='is_number',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='is_words',
        ),
    ]
