# Generated by Django 3.0.5 on 2021-02-07 23:02

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0035_auto_20210207_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='imagefiles',
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_a',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_b',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_c',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_d',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_e',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_f',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 6'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_g',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 7'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_h',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 8'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_i',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 9'),
        ),
        migrations.AddField(
            model_name='variable',
            name='imagefile_j',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 10'),
        ),
    ]
