# Generated by Django 3.0.5 on 2022-11-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
        ('tool', '0035_auto_20221126_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='is_random',
            field=models.BooleanField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='is_video',
            field=models.BooleanField(default=0, verbose_name='Support de passation'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='nb_slide',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Mentaltitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Titre')),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('is_display', models.BooleanField(default=0, verbose_name='En ligne ?')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentaltitles', to='socle.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Mental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, verbose_name='Contenu')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Html éventuel')),
                ('script', models.TextField(blank=True, max_length=255, null=True, verbose_name='script éventuel')),
                ('is_display', models.BooleanField(default=0, verbose_name='En ligne ?')),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('mentaltitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentals', to='tool.Mentaltitle')),
            ],
        ),
    ]
