# Generated by Django 3.0.5 on 2021-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0035_auto_20210216_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_question',
            name='students',
        ),
        migrations.AddField(
            model_name='display_question',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='display_questions', to='account.Student'),
        ),
    ]
