# Generated by Django 3.0.5 on 2021-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0036_auto_20210220_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerplayer',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse'),
        ),
    ]
