# Generated by Django 3.0.5 on 2022-11-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
        ('tool', '0036_auto_20221129_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentaltitle',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='mentaltitles', to='socle.Level'),
        ),
    ]
