# Generated by Django 3.0.5 on 2021-02-07 23:20

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0036_auto_20210208_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_a',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_b',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_c',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_d',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_e',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_f',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_g',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_h',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_i',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='imagefile_j',
        ),
        migrations.CreateModel(
            name='VariableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image 1')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_img', to='tool.Variable')),
            ],
        ),
    ]
