# Generated by Django 3.0.5 on 2022-12-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0037_mentaltitle_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tool.Mental'),
        ),
    ]
