# Generated by Django 3.0.5 on 2021-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0037_auto_20210220_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_question',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
