# Generated by Django 3.0.5 on 2021-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0037_auto_20210208_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='words',
            field=models.CharField(blank=True, max_length=255, verbose_name='Liste de valeurs'),
        ),
    ]
