# Generated by Django 3.0.5 on 2022-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0038_question_mental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='nb_slide',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
    ]
