# Generated by Django 3.0.5 on 2021-02-27 14:17

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0038_auto_20210220_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videocopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tool.models.videocopy_directory_path, verbose_name='Photo')),
                ('teacher', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_videocopy', to='account.Teacher')),
            ],
        ),
    ]
