# Generated by Django 3.0.5 on 2021-02-08 10:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0038_auto_20210208_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrandom',
            name='teachers',
            field=models.ForeignKey(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='qrandom', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='qrandom',
            name='texte',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Enoncé'),
        ),
        migrations.AlterField(
            model_name='qrandom',
            name='title',
            field=models.CharField(blank=True, max_length=20, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='is_mark',
            field=models.BooleanField(default=0, verbose_name='Récupérer les réponses ?'),
        ),
        migrations.AlterField(
            model_name='variableimage',
            name='image',
            field=models.ImageField(default='', upload_to=tool.models.variable_directory_path, verbose_name='Image'),
        ),
    ]
