# Generated by Django 3.0.5 on 2022-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0039_auto_20221202_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentaltitle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
