# Generated by Django 3.0.5 on 2021-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0039_videocopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='is_ranking',
            field=models.BooleanField(default=0, verbose_name='Ordre aléatoire des questions ?'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='is_shuffle',
            field=models.BooleanField(default=0, verbose_name='Ordre aléatoire des réponses ?'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='is_video',
            field=models.BooleanField(default=0, verbose_name='Vidéo-projeter ?'),
        ),
    ]
