# Generated by Django 3.0.5 on 2021-02-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_response'),
        ('tool', '0039_auto_20210208_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrandom',
            name='teachers',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='qrandom', to='account.Teacher'),
        ),
    ]
