# Generated by Django 3.0.5 on 2021-02-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0040_auto_20210208_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrandom',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
