# Generated by Django 3.0.5 on 2021-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0040_auto_20210314_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de publication'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé à partir du'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='is_video',
            field=models.BooleanField(default=0, verbose_name='Vidéo-projection ?'),
        ),
    ]
