# Generated by Django 3.0.5 on 2022-12-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0040_auto_20221203_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mental',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Contenu'),
        ),
    ]
