# Generated by Django 3.0.5 on 2022-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0041_auto_20221203_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='interslide',
            field=models.PositiveIntegerField(blank=True, default=10, verbose_name='Transition entre questions'),
        ),
    ]
