# Generated by Django 3.0.5 on 2021-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0041_auto_20210314_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='is_back',
            field=models.BooleanField(default=0, verbose_name='Retour arrière ?'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='is_video',
            field=models.BooleanField(default=0, verbose_name='Type de passation'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé dès le'),
        ),
    ]
