# Generated by Django 3.0.5 on 2021-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0041_auto_20210208_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='variable'),
        ),
    ]
