# Generated by Django 3.0.5 on 2021-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0042_auto_20210208_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrandom',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titre'),
        ),
    ]
