# Generated by Django 3.0.5 on 2022-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
        ('tool', '0042_auto_20221204_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentaltitle',
            name='levels',
        ),
        migrations.AddField(
            model_name='mental',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='mentaltitles', to='socle.Level'),
        ),
    ]
