# Generated by Django 3.0.5 on 2021-03-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0111_auto_20210314_2121'),
        ('tool', '0043_quizz_is_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='parcours',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='qcm.Parcours'),
        ),
    ]
