# Generated by Django 3.0.5 on 2021-02-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0043_auto_20210208_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='qrandoms',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='tool.Qrandom'),
        ),
    ]
