# Generated by Django 3.0.5 on 2021-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0044_quizz_qrandoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrandom',
            name='qtype',
            field=models.PositiveIntegerField(default=2, editable=False),
        ),
    ]
