# Generated by Django 3.0.5 on 2021-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0111_auto_20210314_2121'),
        ('group', '0015_group_studentprofile'),
        ('tool', '0044_quizz_parcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='quizz', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='parcours',
            field=models.ManyToManyField(blank=True, related_name='quizz', to='qcm.Parcours'),
        ),
    ]
