# Generated by Django 3.0.5 on 2022-12-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0044_auto_20221207_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Formule Tex $$ ..... $$ à afficher'),
        ),
    ]
