# Generated by Django 3.0.5 on 2021-02-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0045_qrandom_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrandom',
            name='calculator',
            field=models.BooleanField(default=0, verbose_name='Calculatrice ?'),
        ),
        migrations.AddField(
            model_name='qrandom',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=20, verbose_name='Durée'),
        ),
    ]
