# Generated by Django 3.0.5 on 2022-12-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0045_question_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writinganswer',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse rédigée'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse attendue'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, default='', verbose_name='Enoncé'),
        ),
    ]
