# Generated by Django 3.0.5 on 2021-04-02 11:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0045_auto_20210320_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Texte'),
        ),
    ]
