# Generated by Django 3.0.5 on 2022-12-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0047_mental_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='interslide',
            field=models.PositiveIntegerField(blank=True, default=10, verbose_name='Transition'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='is_random',
            field=models.BooleanField(default=0, verbose_name='Type de quizz'),
        ),
    ]
