# Generated by Django 3.0.5 on 2021-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0047_auto_20210623_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrandom',
            name='size',
        ),
        migrations.RemoveField(
            model_name='qrandom',
            name='theme',
        ),
        migrations.AddField(
            model_name='question',
            name='size',
            field=models.PositiveIntegerField(choices=[(16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56')], default=20, verbose_name='Taille de police'),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.BooleanField(default=0, verbose_name='Thème ?'),
        ),
    ]
