# Generated by Django 3.0.5 on 2021-06-23 15:55

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0048_auto_20210623_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, default='', upload_to=tool.models.question_directory_path, verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.TextField(blank=True, default='', verbose_name='Vidéo intégrée'),
        ),
    ]
