# Generated by Django 3.0.5 on 2022-12-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0048_auto_20221212_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='custom',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='template pour les exos'),
        ),
    ]
