# Generated by Django 3.0.5 on 2022-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0049_qtype_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='is_sub',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
