# Generated by Django 3.0.5 on 2022-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0051_auto_20221215_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='is_sub',
            field=models.BooleanField(default=0),
        ),
    ]
