# Generated by Django 3.0.5 on 2022-12-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0052_qtype_is_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='is_alea',
            field=models.BooleanField(default=0),
        ),
    ]
