# Generated by Django 3.0.5 on 2022-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0053_qtype_is_alea'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='template_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='template de réponse'),
        ),
    ]
