# Generated by Django 3.0.5 on 2022-12-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0054_qtype_template_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qtype',
            name='template_answer',
        ),
    ]
