# Generated by Django 3.0.5 on 2023-01-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0055_remove_qtype_template_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='is_insert',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='qtype',
            name='is_pseudo',
            field=models.BooleanField(default=0),
        ),
    ]
