# Generated by Django 3.0.5 on 2023-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0056_auto_20230106_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtype',
            name='template',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='template de quizz'),
        ),
    ]
