# Generated by Django 3.0.5 on 2023-01-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0057_auto_20230108_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtype',
            name='template_ans',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='template de réponse'),
        ),
    ]
