# Generated by Django 3.0.5 on 2023-01-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0059_remove_qtype_template_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='mentaltitle',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='tool.Mentaltitle'),
        ),
    ]
