# Generated by Django 3.0.5 on 2023-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0061_auto_20230117_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='mental',
            name='jquery',
            field=models.TextField(blank=True, null=True, verbose_name='Jquery éventuel'),
        ),
        migrations.AlterField(
            model_name='mental',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='Python éventuel'),
        ),
    ]
