# Generated by Django 3.0.5 on 2023-01-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0062_auto_20230118_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mental',
            name='jquery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jquery éventuel'),
        ),
    ]
