# Generated by Django 3.0.5 on 2023-03-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0063_auto_20230118_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='size',
            field=models.PositiveIntegerField(blank=True, choices=[(16, '16'), (24, '24'), (32, '32'), (40, '40'), (48, '48'), (56, '56')], default=56, verbose_name='Taille de police'),
        ),
    ]
