# Generated by Django 3.0.5 on 2023-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0064_auto_20230326_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='mental',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=20, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='delta_duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
