# Generated by Django 3.0.5 on 2023-03-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('tool', '0065_auto_20230328_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentaltitle',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='mentaltitles', to='socle.Level'),
        ),
        migrations.AlterField(
            model_name='mental',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='mentals', to='socle.Level'),
        ),
    ]
