# Generated by Django 3.0.5 on 2023-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('tool', '0066_auto_20230329_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='mental',
            name='subjects',
            field=models.ManyToManyField(related_name='mentals', to='socle.Subject'),
        ),
    ]
