# Generated by Django 3.0.5 on 2023-03-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('tool', '0067_auto_20230329_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentaltitle',
            name='subject',
        ),
        migrations.AddField(
            model_name='mentaltitle',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='mentaltitles', to='socle.Subject'),
        ),
        migrations.AlterField(
            model_name='mental',
            name='mentaltitle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mentals', to='tool.Mentaltitle'),
        ),
    ]
