# Generated by Django 3.0.5 on 2023-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0068_auto_20230330_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Primaire'), (1, 'Collège'), (2, 'Lycée')], default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='ranking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='theme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nombres et calculs'), (1, 'Numération'), (2, 'Géométrie'), (3, 'Grandeurs et mesures'), (4, 'Stats proba'), (5, 'Utilitaires')], default=0),
        ),
    ]
