# Generated by Django 3.0.5 on 2023-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
        ('tool', '0069_auto_20230825_0015'),
    ]

 
