# Generated by Django 3.0.5 on 2023-09-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0104_auto_20230925_2213'),
        ('tool', '0069_auto_20230827_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='folders',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='qcm.Folder'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='parcours',
            field=models.ManyToManyField(blank=True, editable=False, related_name='quizz', to='qcm.Parcours'),
        ),
    ]
