# Generated by Django 3.0.5 on 2023-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0070_auto_20230827_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='theme',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
