# Generated by Django 3.0.5 on 2023-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0071_auto_20230926_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
