# Generated by Django 3.0.5 on 2020-05-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.CharField(default='', editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('shortname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abréviation')),
                ('cycle', models.CharField(choices=[('c1', 'Cycle 1'), ('c2', 'Cycle 2'), ('c3', 'Cycle 3'), ('c4', 'Cycle 4'), ('c5', 'Cycle 5')], default='c1', max_length=10, verbose_name='Cycle')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('themes', models.ManyToManyField(default='', related_name='theme_level', to='socle.Theme', verbose_name='Thèmes')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Nom')),
                ('level', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='knowledges', to='socle.Level', verbose_name='Niveau')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledges', to='socle.Theme', verbose_name='Thème')),
            ],
        ),
    ]
