# Generated by Django 3.0.5 on 2020-07-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('color', models.CharField(default='', editable=False, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='subject',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill', to='socle.Subject', verbose_name='Enseignement'),
        ),
        migrations.AddField(
            model_name='theme',
            name='subject',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='theme', to='socle.Subject', verbose_name='Enseignement'),
        ),
    ]
