# Generated by Django 3.0.5 on 2020-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_auto_20200723_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='shortname',
            field=models.CharField(default='', max_length=10, verbose_name='Abréviation'),
        ),
    ]
