# Generated by Django 3.0.5 on 2020-05-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='knowledges', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledges', to='socle.Theme', verbose_name='Thème'),
        ),
    ]
