# Generated by Django 3.0.5 on 2020-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0003_subject_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='Nom'),
        ),
    ]
