# Generated by Django 3.0.5 on 2020-12-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0004_auto_20201024_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='socle.Theme', verbose_name='Thème'),
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='socle.Theme', verbose_name='Thème')),
            ],
        ),
        migrations.AddField(
            model_name='knowledge',
            name='waiting',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='socle.Waiting', verbose_name='Attendu'),
        ),
    ]
