# Generated by Django 3.0.5 on 2020-12-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0005_auto_20201212_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to='socle.Level', verbose_name='Niveau'),
        ),
    ]
