# Generated by Django 3.0.5 on 2020-12-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0006_waiting_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nom'),
        ),
    ]
