# Generated by Django 3.0.5 on 2021-04-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_auto_20201215_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
