# Generated by Django 3.0.5 on 2022-09-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0007_subject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Active ?'),
        ),
    ]
