# Generated by Django 3.0.5 on 2023-01-06 09:01

from django.db import migrations, models
import socle.models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0008_level_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='canvasimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to=socle.models.image_directory_path, verbose_name='Image'),
        ),
    ]
