# Generated by Django 3.0.5 on 2023-08-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0010_auto_20230106_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Nom')),
                ('level', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bos', to='socle.Level', verbose_name='Niveau')),
                ('subject', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bos', to='socle.Subject', verbose_name='Enseignement')),
            ],
        ),
    ]
