# Generated by Django 3.0.5 on 2023-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0011_bo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bo',
            name='link',
        ),
        migrations.AddField(
            model_name='bo',
            name='document',
            field=models.CharField(default='', max_length=255, verbose_name='url document accompagnement'),
        ),
        migrations.AddField(
            model_name='bo',
            name='programme',
            field=models.CharField(default='', max_length=255, verbose_name='url programme'),
        ),
        migrations.AddField(
            model_name='bo',
            name='titre',
            field=models.CharField(default='', max_length=255, verbose_name='Nom'),
        ),
    ]
