# Generated by Django 3.0.5 on 2023-08-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socle', '0012_auto_20230830_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bo',
            old_name='titre',
            new_name='title',
        ),
    ]
