# Generated by Django 3.0.5 on 2023-02-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_connexion'),
        ('bibliotex', '0018_exotex_is_annals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotationtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Commentaire')),
                ('emoticon', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, verbose_name='Emoticon')),
                ('relationtex', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='annotationtex', to='bibliotex.Relationtex')),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='annotationtex', to='account.Student')),
            ],
        ),
    ]
