# Generated by Django 3.0.5 on 2023-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0019_annotationtex'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotex',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
