# Generated by Django 3.0.5 on 2023-03-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0094_auto_20230326_0512'),
        ('account', '0030_connexion'),
        ('bibliotex', '0020_bibliotex_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtex',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='relationtexs', to='qcm.Relationship', verbose_name='Exercices'),
        ),
        migrations.AlterField(
            model_name='relationtex',
            name='students',
            field=models.ManyToManyField(blank=True, editable=False, related_name='relationtexs', to='account.Student'),
        ),
    ]
