# Generated by Django 3.0.5 on 2023-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0022_auto_20230418_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='bloc_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
