# Generated by Django 3.0.5 on 2023-09-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0023_exotex_bloc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='is_read',
            field=models.BooleanField(default=0, verbose_name='Relu et vérifié ?'),
        ),
    ]
