# Generated by Django 3.0.5 on 2023-09-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0102_docperso_subject'),
        ('account', '0032_auto_20230605_2102'),
        ('socle', '0013_auto_20230830_1633'),
        ('bibliotex', '0025_auto_20230904_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='exotex',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exotexs', to='qcm.Exercise', verbose_name='Exercices connexes'),
        ),
        migrations.AlterField(
            model_name='exotex',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_exotexs', to='account.Teacher'),
        ),
        migrations.AlterField(
            model_name='exotex',
            name='knowledge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_exotexs', to='socle.Knowledge', verbose_name='Savoir faire associé'),
        ),
        migrations.AlterField(
            model_name='exotex',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_exotexs', to='socle.Level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='exotex',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_exotexs', to='socle.Subject', verbose_name='Enseignement associé'),
        ),
        migrations.AlterField(
            model_name='exotex',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_exotexs', to='socle.Theme', verbose_name='Thème'),
        ),
    ]
