# Generated by Django 3.0.5 on 2023-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0103_docperso_is_archive'),
        ('bibliotex', '0026_auto_20230913_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationtex',
            name='relationships',
        ),
        migrations.AddField(
            model_name='relationtex',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='relationtexs', to='qcm.Exercise', verbose_name='Exercices'),
        ),
    ]
