# Generated by Django 3.0.5 on 2023-09-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0027_auto_20230916_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationtex',
            name='content',
        ),
        migrations.RemoveField(
            model_name='relationtex',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='relationtex',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='relationtex',
            name='correction_html',
        ),
    ]
