# Generated by Django 3.0.5 on 2023-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0103_docperso_is_archive'),
        ('bibliotex', '0028_auto_20230921_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotex',
            name='parcours',
            field=models.ManyToManyField(blank=True, editable=False, related_name='bibliotexs', to='qcm.Parcours'),
        ),
    ]
