# Generated by Django 3.0.5 on 2023-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0103_docperso_is_archive'),
        ('bibliotex', '0030_auto_20230925_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotex',
            name='folders',
            field=models.ManyToManyField(blank=True, editable=False, related_name='bibliotexs', to='qcm.Folder'),
        ),
        migrations.AlterField(
            model_name='bibliotex',
            name='parcours',
            field=models.ManyToManyField(blank=True, editable=False, related_name='bibliotexs', to='qcm.Parcours'),
        ),
    ]
