# Generated by Django 3.0.5 on 2023-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0105_auto_20230926_1737'),
        ('bibliotex', '0031_auto_20230925_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotex',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='bibliotexs', to='qcm.Folder'),
        ),
        migrations.AlterField(
            model_name='bibliotex',
            name='parcours',
            field=models.ManyToManyField(blank=True, related_name='bibliotexs', to='qcm.Parcours'),
        ),
    ]
