# Generated by Django 3.0.5 on 2023-09-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotex', '0032_auto_20230926_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotex',
            name='two_cols',
            field=models.BooleanField(default=0, verbose_name='Colonnes ?'),
        ),
    ]
